import { z } from 'zod'

const emptyToNull=z.string().trim().max(500).optional().nullable()
export const quoteSizeSchema=z.object({size:z.string().trim().min(1).max(20),quantity:z.coerce.number().int().positive(),position:z.coerce.number().int().min(0).max(999)}).strict()
export const quoteItemSchema=z.object({id:z.string().uuid().optional(),product_id:z.string().uuid().optional().nullable(),description:z.string().trim().min(2).max(300),product_type:emptyToNull,model:emptyToNull,fabric_id:z.string().uuid().optional().nullable(),fabric_name_snapshot:emptyToNull,color:emptyToNull,customization_type:z.enum(['embroidery','silk','dtf','sublimation','none','other']),quantity:z.coerce.number().int().positive(),unit_price:z.coerce.number().min(0),unit_cost:z.coerce.number().min(0),cost_source:z.enum(['manual','calculated','catalog','historical']),discount_amount:z.coerce.number().min(0).default(0),notes:z.string().trim().max(1000).optional().nullable(),position:z.coerce.number().int().min(0).max(999),sizes:z.array(quoteSizeSchema).max(30)}).strict()
export const quoteDraftSchema=z.object({opportunity_id:z.string().uuid(),contact_id:z.string().uuid().optional().nullable(),valid_until:z.string().date(),desired_delivery_date:z.string().date(),payment_term_id:z.string().uuid(),commercial_notes:z.string().trim().max(3000).optional().nullable(),internal_notes:z.string().trim().max(3000).optional().nullable(),discount_amount:z.coerce.number().min(0),freight_amount:z.coerce.number().min(0),additional_amount:z.coerce.number().min(0),items:z.array(quoteItemSchema).min(1).max(100)}).strict()
export const discountRequestSchema=z.object({quote_id:z.string().uuid(),reason:z.string().trim().min(5).max(1000)}).strict()
export const discountDecisionSchema=z.object({approval_id:z.string().uuid(),approve:z.boolean(),notes:z.string().trim().min(2).max(1000)}).strict()
export const proposalResponseSchema=z.object({token:z.string().min(40).max(256),name:z.string().trim().min(2).max(120),job_title:z.string().trim().max(120).optional().nullable(),notes:z.string().trim().max(2000).optional().nullable()}).strict()
