'use client'

import { useState,useTransition } from 'react'
import { CheckCircle2,Loader2,MessageSquareText,Printer,ShieldCheck } from 'lucide-react'
import { respondProposal } from '@/app/proposta/actions'
import { customizationLabel } from '@/lib/domain/quotes/customization'
import { formatBRL,formatDate } from '@/lib/utils'
import type { PublicProposal as PublicProposalData } from '@/types/quotes'

export function PublicProposal({proposal,token}:{proposal:PublicProposalData;token:string}){
  const [response,setResponse]=useState<'approve'|'request_change'|null>(null);const [name,setName]=useState('');const [job,setJob]=useState('');const [notes,setNotes]=useState('');const [done,setDone]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition()
  const submit=()=>response&&start(async()=>{setError('');const result=await respondProposal(response,{token,name,job_title:job||null,notes:notes||null});if(result.success){setDone(response==='approve'?'Proposta aprovada com sucesso.':'Solicitação enviada ao responsável comercial.');setResponse(null);return}setError(result.error??'Não foi possível registrar a resposta.')})
  return <main className="proposal-page min-h-screen overflow-x-hidden bg-[#f4f5f2] p-3 text-zinc-900 [overflow-wrap:anywhere] sm:p-8 print:bg-white print:p-0">
    <article className="mx-auto min-w-0 max-w-5xl overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm print:max-w-none print:border-0 print:shadow-none">
      <header className="bg-zinc-950 p-5 text-white sm:p-9"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-sm font-semibold tracking-[0.18em] text-green-400">SELMA BORDADOS</p><h1 className="mt-3 text-2xl font-semibold sm:text-3xl">Proposta comercial</h1><p className="mt-1 text-sm text-zinc-400">{proposal.quote_number} · versão {proposal.version_number}</p></div><div className="rounded-xl border border-white/10 bg-white/5 p-3 text-left sm:text-right"><p className="text-xs uppercase tracking-wide text-zinc-400">Válida até</p><strong className="mt-1 block">{formatDate(proposal.valid_until)}</strong></div></div></header>
      <section className="min-w-0 space-y-7 p-5 sm:p-9">
        <div className="grid min-w-0 gap-5 rounded-xl bg-zinc-50 p-4 sm:grid-cols-2"><div className="min-w-0"><p className="proposal-label">Cliente</p><strong className="mt-1 block text-lg">{proposal.customer.name}</strong>{proposal.customer.contact_name&&<p className="text-sm">{proposal.customer.contact_name}</p>}<p className="mt-1 break-words text-sm text-zinc-500">{[proposal.customer.phone,proposal.customer.email].filter(Boolean).join(' · ')}</p></div><div className="min-w-0"><p className="proposal-label">Condições</p><p className="mt-1"><strong>Entrega:</strong> {formatDate(proposal.desired_delivery_date)}</p><p className="text-sm text-zinc-600">{proposal.commercial.payment_term}</p></div></div>
        <section className="min-w-0"><div className="mb-3 flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><div className="min-w-0"><p className="proposal-label">Produtos</p><h2 className="mt-1 text-lg font-semibold">Itens desta versão</h2></div><span className="text-xs text-zinc-500">Valores em BRL</span></div><div className="min-w-0 space-y-3">{proposal.items.map((item,index)=><article key={`${item.description}-${index}`} className="proposal-item min-w-0 rounded-xl border border-zinc-200 p-4"><div className="flex min-w-0 flex-col justify-between gap-2 sm:flex-row"><div className="min-w-0"><strong>{item.description}</strong><p className="mt-1 break-words text-sm text-zinc-500">{[item.product_type,item.model,item.fabric,item.color,customizationLabel(item.customization_type)].filter(Boolean).join(' · ')}</p></div><strong className="shrink-0">{formatBRL(Number(item.subtotal))}</strong></div><div className="mt-3 flex flex-wrap items-center gap-2 text-sm"><span>{item.quantity} peças × {formatBRL(Number(item.unit_price))}</span>{item.discount_amount>0&&<span className="text-zinc-500">· desconto {formatBRL(Number(item.discount_amount))}</span>}</div>{item.sizes.length>0&&<div className="mt-3 flex flex-wrap gap-2">{item.sizes.map(size=><span key={size.size} className="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-medium">{size.size}: {size.quantity}</span>)}</div>}{item.notes&&<p className="mt-3 text-sm text-zinc-600">{item.notes}</p>}</article>)}</div></section>
        <div className="grid gap-6 md:grid-cols-[1fr_360px]"><div>{proposal.commercial.notes&&<div><p className="proposal-label">Observações comerciais</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-700">{proposal.commercial.notes}</p></div>}</div><div className="rounded-xl bg-zinc-950 p-5 text-white"><MoneyRow label="Subtotal" value={proposal.subtotal}/>{proposal.discount_amount>0&&<MoneyRow label="Desconto" value={-proposal.discount_amount}/>}<MoneyRow label="Frete" value={proposal.freight_amount}/><MoneyRow label="Adicionais" value={proposal.additional_amount}/><div className="mt-3 border-t border-white/15 pt-3"><MoneyRow label="Total" value={proposal.total_amount} strong/></div></div></div>
        {(done||!proposal.can_respond)&&<div className="flex gap-3 rounded-xl bg-green-50 p-4 text-green-800"><ShieldCheck className="mt-0.5 size-5 shrink-0"/><div><strong>{done||responseStatus(proposal.status)}</strong><p className="mt-0.5 text-sm">Esta página representa exatamente a versão {proposal.version_number} da proposta.</p></div></div>}
        <div className="proposal-actions flex flex-col gap-3 sm:flex-row">{proposal.can_respond&&!done&&<><button type="button" onClick={()=>{setResponse('approve');setError('')}} className="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl bg-green-600 px-4 font-semibold text-white hover:bg-green-700"><CheckCircle2/>Aprovar proposta</button><button type="button" onClick={()=>{setResponse('request_change');setError('')}} className="flex min-h-12 flex-1 items-center justify-center gap-2 rounded-xl border border-zinc-300 px-4 font-semibold hover:bg-zinc-50"><MessageSquareText/>Solicitar alteração</button></>}<button type="button" onClick={()=>window.print()} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-zinc-300 px-4 font-semibold hover:bg-zinc-50"><Printer/>Imprimir</button></div>
        {response&&<section className="proposal-response space-y-3 rounded-xl border border-zinc-200 bg-zinc-50 p-4 sm:p-5"><div><h2 className="font-semibold">{response==='approve'?'Confirmar aprovação':'O que você gostaria de alterar?'}</h2><p className="mt-1 text-sm text-zinc-500">Sua resposta será enviada ao responsável comercial.</p></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Seu nome *<input className="mt-1 w-full rounded-lg border border-zinc-300 bg-white p-2.5 outline-none focus:border-green-600" value={name} onChange={event=>setName(event.target.value)}/></label><label className="text-sm">Cargo<input className="mt-1 w-full rounded-lg border border-zinc-300 bg-white p-2.5 outline-none focus:border-green-600" value={job} onChange={event=>setJob(event.target.value)}/></label></div><label className="block text-sm">{response==='approve'?'Observação':'Alteração solicitada *'}<textarea className="mt-1 min-h-28 w-full rounded-lg border border-zinc-300 bg-white p-2.5 outline-none focus:border-green-600" value={notes} onChange={event=>setNotes(event.target.value)}/></label>{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" className="rounded-lg border border-zinc-300 px-4 py-2" onClick={()=>setResponse(null)}>Cancelar</button><button type="button" disabled={pending||name.trim().length<2||(response==='request_change'&&notes.trim().length<3)} onClick={submit} className="rounded-lg bg-zinc-950 px-4 py-2 font-medium text-white disabled:opacity-50">{pending&&<Loader2 className="mr-1 inline size-4 animate-spin"/>}Confirmar</button></div></section>}
      </section>
      <footer className="border-t border-zinc-200 px-5 py-5 text-center text-xs text-zinc-500 sm:px-9">Selma Bordados · Proposta {proposal.quote_number} · versão {proposal.version_number}</footer>
    </article>
    <style>{`@media print{@page{size:A4;margin:10mm}.proposal-page{padding:0!important}.proposal-actions,.proposal-response{display:none!important}.proposal-item{break-inside:avoid}.proposal-page article{border-radius:0!important}}`}</style>
  </main>
}

function MoneyRow({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className={`flex justify-between gap-4 py-1 ${strong?'text-lg':''}`}><span className="text-zinc-300">{label}</span><strong>{formatBRL(Number(value))}</strong></div>}
function responseStatus(status:string){if(status==='approved')return'Proposta aprovada.';if(status==='change_requested')return'Alteração solicitada.';if(status==='rejected')return'Proposta recusada.';return'Proposta registrada.'}
