'use client'

import { useMemo,useState,useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowDown,ArrowUp,ChevronDown,Copy,ExternalLink,FileClock,Loader2,Plus,Save,Send,ShoppingCart,Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import { convertQuote,createQuoteVersion,decideQuoteApproval,duplicateQuote,requestQuoteApproval,saveQuote,sendQuote } from '@/app/crm/orcamentos/actions'
import { HealthBadge,SectionCard } from '@/components/crm/CrmUi'
import { Button } from '@/components/ui/button'
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from '@/components/ui/dialog'
import { calculateQuotePricing,gradeMatchesQuantity } from '@/lib/domain/quotes/pricing'
import { CUSTOMIZATION_OPTIONS } from '@/lib/domain/quotes/customization'
import { formatBRL } from '@/lib/utils'
import type { CostSource,DiscountApproval,PaymentTermTemplate,Quote,QuoteItem } from '@/types/quotes'

type Opportunity={id:string;title:string;customer_id:string;contact_id:string|null;assigned_user_id:string;desired_delivery_date:string|null;estimated_quantity?:number;customer?:{id:string;nome:string;contacts?:Array<{id:string;name:string;active:boolean}>}|null}
type PreliminarySafeDate={earliest_safe_date:string;risk_level:string;calculation_mode:string;explanation:unknown[]}|null
type DraftItem={description:string;product_type:string;model:string;fabric_id:string|null;fabric_name_snapshot:string;color:string;customization_type:'embroidery'|'silk'|'dtf'|'sublimation'|'none'|'other';quantity:number;unit_price:number;unit_cost:number;cost_source:CostSource;discount_amount:number;notes:string;position:number;sizes:Array<{size:string;quantity:number;position:number}>}
type ActionResult={success:boolean;error?:string;data?:Record<string,unknown>}
const emptyItem=(position=0):DraftItem=>({description:'',product_type:'Camiseta',model:'',fabric_id:null,fabric_name_snapshot:'',color:'',customization_type:'none',quantity:1,unit_price:0,unit_cost:0,cost_source:'manual',discount_amount:0,notes:'',position,sizes:[]})

export function QuoteEditor({quote,opportunity,terms,fabrics,defaultValidUntil,minimumMarginPercent,requireMarginApproval,approvals=[],canApprove=false,preliminarySafeDate=null}:{quote?:Quote|null;opportunity:Opportunity;terms:PaymentTermTemplate[];fabrics:Array<{id:string;codigo:string;descricao:string;valor_unitario:number|null}>;defaultValidUntil:string;minimumMarginPercent:number;requireMarginApproval:boolean;approvals?:DiscountApproval[];canApprove?:boolean;preliminarySafeDate?:PreliminarySafeDate}){
  const router=useRouter();const [pending,start]=useTransition();const version=quote?.current_version
  const [form,setForm]=useState({contact_id:quote?.contact_id??opportunity.contact_id??null,valid_until:quote?.valid_until??defaultValidUntil,desired_delivery_date:quote?.desired_delivery_date??opportunity.desired_delivery_date??'',payment_term_id:quote?.payment_term_id??terms[0]?.id??'',commercial_notes:quote?.commercial_notes??'',internal_notes:quote?.internal_notes??'',discount_amount:Number(quote?.discount_amount??0),freight_amount:Number(quote?.freight_amount??0),additional_amount:Number(quote?.additional_amount??0)})
  const [items,setItems]=useState<DraftItem[]>(version?.items?.length?[...version.items].sort((a,b)=>a.position-b.position).map(fromItem):[emptyItem()])
  const [dirty,setDirty]=useState(false)
  const [summaryOpen,setSummaryOpen]=useState(false)
  const [approvalOpen,setApprovalOpen]=useState(false);const [approvalReason,setApprovalReason]=useState('');const [decision,setDecision]=useState<{id:string;approve:boolean}|null>(null);const [decisionNotes,setDecisionNotes]=useState('');const [versionOpen,setVersionOpen]=useState(false);const [newValidity,setNewValidity]=useState(form.valid_until);const [proposalUrl,setProposalUrl]=useState('')
  const pricing=useMemo(()=>calculateQuotePricing({items:items.map(item=>({quantity:item.quantity,unitPrice:item.unit_price,unitCost:item.unit_cost,discountAmount:item.discount_amount})),discountAmount:form.discount_amount,freightAmount:form.freight_amount,additionalAmount:form.additional_amount}),[items,form.discount_amount,form.freight_amount,form.additional_amount])
  const policyWarning=requireMarginApproval&&pricing.marginPercent<minimumMarginPercent
  const canEdit=!quote||!['converted','archived'].includes(quote.status)
  const updateForm=<K extends keyof typeof form>(key:K,value:(typeof form)[K])=>{setDirty(true);setForm(current=>({...current,[key]:value}))}
  const updateItem=(index:number,patch:Partial<DraftItem>)=>{setDirty(true);setItems(current=>current.map((item,position)=>position===index?{...item,...patch}:item))}
  const moveItem=(index:number,direction:-1|1)=>{setDirty(true);setItems(current=>{const target=index+direction;if(target<0||target>=current.length)return current;const copy=[...current];[copy[index],copy[target]]=[copy[target],copy[index]];return copy})}
  const payload=()=>({opportunity_id:opportunity.id,...form,items:items.map((item,position)=>({...item,position,product_id:null,notes:item.notes||null,product_type:item.product_type||null,model:item.model||null,fabric_name_snapshot:item.fabric_name_snapshot||null,color:item.color||null}))})
  const validate=()=>{const invalid=items.find(item=>!gradeMatchesQuantity(item.quantity,item.sizes));if(invalid)return`A grade de “${invalid.description||'item'}” não soma a quantidade.`;if(!form.contact_id)return'Selecione o contato do cliente.';if(!form.payment_term_id)return'Selecione uma condição de pagamento.';if(items.some(item=>item.description.trim().length<2))return'Informe a descrição de todos os itens.';return null}
  const performSave=async():Promise<ActionResult>=>{const error=validate();if(error)return{success:false,error};return saveQuote(quote?.id??null,payload())}
  const run=(work:()=>Promise<ActionResult>,message:string,onSuccess?:((result:ActionResult)=>void))=>start(async()=>{const result=await work();if(!result.success){toast.error(result.error??'Não foi possível concluir a ação.');return}toast.success(message);onSuccess?.(result);router.refresh()})
  const persist=()=>run(performSave,'Rascunho salvo.',result=>{setDirty(false);const id=result.data?.id;if(id&&!quote)router.push(`/crm/orcamentos/${id}`)})
  const generateProposal=()=>quote&&run(async()=>{if(dirty)return{success:false,error:'Salve o rascunho antes de gerar a proposta.'};const sent=await sendQuote(quote.id);if(sent.success&&sent.data?.requiresApproval)return{success:false,error:'Esta condição precisa de aprovação comercial antes do envio.'};if(sent.success&&sent.data?.token){const url=`${location.origin}/proposta/${sent.data.token}`;setProposalUrl(url);try{await navigator.clipboard.writeText(url)}catch{}}return sent},'Proposta pronta. O link foi gerado.')
  const convert=()=>quote&&run(async()=>{const result=await convertQuote(quote.id);if(result.success&&result.data)router.push(`/pedidos/${result.data.orderId}`);return result},'Pedido e recebíveis criados.')

  return <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_340px]">
    <div className="min-w-0 space-y-5">
      <SectionCard title="Cliente e condições" description="Dados vinculados à oportunidade, sem redigitação."><div className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4">
        <Field label="Cliente"><input className="crm-control" disabled value={opportunity.customer?.nome??quote?.customer?.nome??''}/></Field>
        <Field label="Oportunidade"><input className="crm-control" disabled value={opportunity.title}/></Field>
        <Field label="Contato"><select className="crm-control" disabled={!canEdit} value={form.contact_id??''} onChange={event=>updateForm('contact_id',event.target.value||null)}><option value="">Selecione</option>{(opportunity.customer?.contacts??[]).filter(contact=>contact.active).map(contact=><option key={contact.id} value={contact.id}>{contact.name}</option>)}</select></Field>
        <Field label="Condição de pagamento"><select className="crm-control" disabled={!canEdit} value={form.payment_term_id} onChange={event=>updateForm('payment_term_id',event.target.value)}>{terms.map(term=><option key={term.id} value={term.id}>{term.name}</option>)}</select></Field>
        <Field label="Validade"><input type="date" className="crm-control" disabled={!canEdit} value={form.valid_until} onChange={event=>updateForm('valid_until',event.target.value)}/></Field>
        <Field label="Entrega desejada"><input type="date" className="crm-control" disabled={!canEdit} value={form.desired_delivery_date} onChange={event=>updateForm('desired_delivery_date',event.target.value)}/></Field>
        <div className="sm:col-span-2"><p className="text-xs text-muted">Parcelas</p><div className="mt-1 flex min-h-10 flex-wrap items-center gap-1.5">{selectedTerm(terms,form.payment_term_id)?.rules.installments.map((installment,index)=><span key={`${installment.label}-${index}`} className="rounded-full bg-surface-hover px-2.5 py-1 text-xs">{installment.label} · {installment.percent}%</span>)}</div></div>
      </div></SectionCard>

      {preliminarySafeDate&&<SectionCard title="Viabilidade preliminar de entrega" description="Estimativa operacional anterior à ficha técnica, ao BOM e às reservas reais."><div className="grid gap-3 p-4 sm:grid-cols-3"><div><p className="text-xs text-muted">Entrega desejada</p><strong className="mt-1 block text-sm">{form.desired_delivery_date?new Date(`${form.desired_delivery_date}T12:00:00`).toLocaleDateString('pt-BR'):'Não informada'}</strong></div><div><p className="text-xs text-muted">Primeira data segura estimada</p><strong className="mt-1 block text-sm">{new Date(`${preliminarySafeDate.earliest_safe_date}T12:00:00`).toLocaleDateString('pt-BR')}</strong></div><div><p className="text-xs text-muted">Risco preliminar</p><div className="mt-1"><HealthBadge kind={preliminarySafeDate.risk_level==='safe'?'success':preliminarySafeDate.risk_level==='attention'?'warning':'danger'} label={preliminarySafeDate.risk_level==='safe'?'Seguro':preliminarySafeDate.risk_level==='attention'?'Atenção':'Alto risco'}/></div></div></div></SectionCard>}

      <SectionCard title="Itens, grade e personalização" description="Custo e preço permanecem por item." action={canEdit?<Button type="button" variant="outline" onClick={()=>{setDirty(true);setItems(current=>[...current,emptyItem(current.length)])}}><Plus/>Adicionar item</Button>:undefined}>
        <div className="space-y-3 p-4">{items.map((item,index)=><article key={index} className="rounded-xl border p-3 sm:p-4" style={{borderColor:'var(--border-subtle)',background:'var(--surface-subtle)'}}>
          <div className="mb-3 flex items-center justify-between gap-3"><div><strong className="text-sm">Item {index+1}</strong><span className="ml-2 text-xs text-muted">{formatBRL(item.quantity*item.unit_price-item.discount_amount)}</span></div>{canEdit&&<div className="flex gap-1"><Button type="button" size="icon-xs" variant="ghost" aria-label="Mover item para cima" disabled={index===0} onClick={()=>moveItem(index,-1)}><ArrowUp/></Button><Button type="button" size="icon-xs" variant="ghost" aria-label="Mover item para baixo" disabled={index===items.length-1} onClick={()=>moveItem(index,1)}><ArrowDown/></Button><Button type="button" size="icon-xs" variant="ghost" aria-label="Duplicar item" onClick={()=>{setDirty(true);setItems(current=>[...current.slice(0,index+1),{...item,sizes:item.sizes.map(size=>({...size}))},...current.slice(index+1)])}}><Copy/></Button><Button type="button" size="icon-xs" variant="destructive" aria-label="Excluir item" disabled={items.length===1} onClick={()=>{setDirty(true);setItems(current=>current.filter((_,position)=>position!==index))}}><Trash2/></Button></div>}</div>
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <Field label="Descrição" className="sm:col-span-2"><input className="crm-control" disabled={!canEdit} value={item.description} onChange={event=>updateItem(index,{description:event.target.value})}/></Field>
            <Field label="Tipo de produto"><input className="crm-control" disabled={!canEdit} value={item.product_type} onChange={event=>updateItem(index,{product_type:event.target.value})}/></Field>
            <Field label="Modelo"><input className="crm-control" disabled={!canEdit} value={item.model} onChange={event=>updateItem(index,{model:event.target.value})}/></Field>
            <Field label="Tecido"><select className="crm-control" disabled={!canEdit} value={item.fabric_id??''} onChange={event=>{const fabric=fabrics.find(candidate=>candidate.id===event.target.value);updateItem(index,{fabric_id:fabric?.id??null,fabric_name_snapshot:fabric?`${fabric.codigo} · ${fabric.descricao}`:'',unit_cost:fabric?.valor_unitario??item.unit_cost,cost_source:fabric?'catalog':'manual'})}}><option value="">Não informado</option>{fabrics.map(fabric=><option key={fabric.id} value={fabric.id}>{fabric.codigo} · {fabric.descricao}</option>)}</select></Field>
            <Field label="Cor"><input className="crm-control" disabled={!canEdit} value={item.color} onChange={event=>updateItem(index,{color:event.target.value})}/></Field>
            <Field label="Personalização"><select className="crm-control" disabled={!canEdit} value={item.customization_type} onChange={event=>updateItem(index,{customization_type:event.target.value as DraftItem['customization_type']})}>{CUSTOMIZATION_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select></Field>
            <NumberField label="Quantidade" disabled={!canEdit} value={item.quantity} integer onChange={value=>updateItem(index,{quantity:value})}/>
            <NumberField label="Preço unitário" disabled={!canEdit} value={item.unit_price} onChange={value=>updateItem(index,{unit_price:value})}/>
            <NumberField label="Desconto do item" disabled={!canEdit} value={item.discount_amount} onChange={value=>updateItem(index,{discount_amount:value})}/>
            <NumberField label="Custo unitário" disabled={!canEdit} value={item.unit_cost} onChange={value=>updateItem(index,{unit_cost:value,cost_source:'manual'})}/>
            <Field label="Fonte do custo"><select className="crm-control" disabled={!canEdit} value={item.cost_source} onChange={event=>updateItem(index,{cost_source:event.target.value as CostSource})}><option value="manual">Manual</option><option value="calculated">Calculado</option><option value="catalog">Catálogo</option><option value="historical">Histórico</option></select></Field>
            <Field label="Grade" className="sm:col-span-2"><input className="crm-control" disabled={!canEdit} placeholder="PP:10, P:25, M:40" value={item.sizes.map(size=>`${size.size}:${size.quantity}`).join(', ')} onChange={event=>updateItem(index,{sizes:parseGrade(event.target.value)})}/>{item.sizes.length>0&&<p className={`mt-1 text-xs ${gradeMatchesQuantity(item.quantity,item.sizes)?'text-green-600':'text-rose-600'}`}>Grade: {item.sizes.reduce((sum,size)=>sum+size.quantity,0)} de {item.quantity} peças</p>}</Field>
            <Field label="Observação" className="sm:col-span-2 xl:col-span-4"><input className="crm-control" disabled={!canEdit} value={item.notes} onChange={event=>updateItem(index,{notes:event.target.value})}/></Field>
          </div>
        </article>)}</div>
      </SectionCard>

      <SectionCard title="Observações" description="A nota interna nunca aparece para o cliente."><div className="grid gap-3 p-4 md:grid-cols-2"><Field label="Observações comerciais"><textarea className="crm-control min-h-28 py-2" disabled={!canEdit} value={form.commercial_notes} onChange={event=>updateForm('commercial_notes',event.target.value)}/></Field><Field label="Notas internas"><textarea className="crm-control min-h-28 py-2" disabled={!canEdit} value={form.internal_notes} onChange={event=>updateForm('internal_notes',event.target.value)}/></Field></div></SectionCard>

      {approvals.length>0&&<SectionCard title="Aprovações comerciais" description="Histórico de decisões preservado."><div className="divide-y" style={{borderColor:'var(--border-subtle)'}}>{approvals.map(approval=><div key={approval.id} className="flex flex-col justify-between gap-3 p-4 sm:flex-row sm:items-center"><div className="text-sm"><div className="flex items-center gap-2"><strong>{approval.status==='pending'?'Pendente':approval.status==='approved'?'Aprovada':approval.status==='rejected'?'Rejeitada':'Cancelada'}</strong><span className="text-muted">desconto {Number(approval.discount_percent).toFixed(2)}% · margem {Number(approval.margin_percent).toFixed(2)}%</span></div><p className="mt-1 text-xs text-muted">{approval.reason}</p></div>{canApprove&&approval.status==='pending'&&<div className="flex gap-2"><Button variant="outline" onClick={()=>{setDecision({id:approval.id,approve:false});setDecisionNotes('')}}>Rejeitar</Button><Button onClick={()=>{setDecision({id:approval.id,approve:true});setDecisionNotes('Aprovado')}}>Aprovar</Button></div>}</div>)}</div></SectionCard>}
    </div>

    <aside className="sticky bottom-3 z-10 min-w-0 space-y-3 lg:top-20 lg:bottom-auto">
      <section className="crm-card min-w-0 overflow-hidden bg-card/95 p-4 shadow-lg backdrop-blur lg:shadow-sm"><button type="button" className="flex w-full min-w-0 items-center justify-between gap-3 text-left lg:cursor-default" aria-expanded={summaryOpen} onClick={()=>setSummaryOpen(open=>!open)}><span className="min-w-0"><span className="block font-semibold">Resumo financeiro</span><span className="mt-0.5 block text-sm font-semibold lg:hidden">{formatBRL(pricing.totalAmount)}</span></span><span className="flex shrink-0 items-center gap-2">{policyWarning?<HealthBadge kind="warning" label="Aprovação necessária"/>:<HealthBadge kind="success" label="Dentro da política"/>}<ChevronDown className={`size-4 transition-transform lg:hidden ${summaryOpen?'rotate-180':''}`}/></span></button><div className={`${summaryOpen?'block':'hidden'} lg:block`}><div className="mt-4 min-w-0 space-y-2"><MoneyRow label="Subtotal" value={pricing.subtotal}/><MoneyRow label="Desconto" value={-pricing.discountAmount}/><MoneyRow label="Frete" value={pricing.freightAmount}/><MoneyRow label="Adicionais" value={pricing.additionalAmount}/><div className="border-t pt-3" style={{borderColor:'var(--border-subtle)'}}><MoneyRow label="Total" value={pricing.totalAmount} strong/></div><MoneyRow label="Custo estimado" value={pricing.estimatedCost}/><MoneyRow label="Lucro estimado" value={pricing.estimatedProfit}/><div className="grid min-w-0 grid-cols-2 gap-2 pt-2"><div className="min-w-0 rounded-lg bg-surface-hover p-2"><p className="text-xs text-muted">Margem</p><strong>{pricing.marginPercent.toFixed(2)}%</strong></div><div className="min-w-0 rounded-lg bg-surface-hover p-2"><p className="text-xs text-muted">Markup</p><strong>{pricing.markup?.toFixed(2)??'—'}x</strong></div></div></div>
        {canEdit&&<div className="mt-4 grid min-w-0 grid-cols-3 gap-2"><NumberField label="Desconto" value={form.discount_amount} onChange={value=>updateForm('discount_amount',value)}/><NumberField label="Frete" value={form.freight_amount} onChange={value=>updateForm('freight_amount',value)}/><NumberField label="Adicionais" value={form.additional_amount} onChange={value=>updateForm('additional_amount',value)}/></div>}
        {policyWarning&&<div className="mt-3 rounded-lg bg-amber-500/10 p-3 text-xs text-amber-700 dark:text-amber-400"><strong>Margem abaixo da política comercial.</strong><p className="mt-1">Atual: {pricing.marginPercent.toFixed(2)}% · Mínimo: {minimumMarginPercent.toFixed(2)}%</p></div>}</div>
      </section>
      <div className="crm-card flex flex-wrap gap-2 p-3">
        {canEdit&&<Button className="flex-1" disabled={pending} onClick={persist}>{pending?<Loader2 className="animate-spin"/>:<Save/>}Salvar rascunho</Button>}
        {quote&&['draft','ready'].includes(quote.status)&&<Button variant="outline" disabled={pending} onClick={()=>setApprovalOpen(true)}>Solicitar aprovação</Button>}
        {quote&&canEdit&&<Button variant="outline" disabled={pending} onClick={generateProposal}><Send/>Gerar proposta</Button>}
        {quote&&version?.sent_at&&canEdit&&<Button variant="outline" disabled={pending} onClick={()=>{setNewValidity(form.valid_until);setVersionOpen(true)}}><FileClock/>Nova versão</Button>}
        {quote&&<Button variant="ghost" disabled={pending} onClick={()=>run(()=>duplicateQuote(quote.id),'Orçamento duplicado.',result=>{if(result.data?.id)router.push(`/crm/orcamentos/${result.data.id}`)})}><Copy/>Duplicar</Button>}
        {quote?.status==='approved'&&<Button className="w-full bg-blue-600 hover:bg-blue-500" disabled={pending} onClick={convert}><ShoppingCart/>Converter em pedido</Button>}
      </div>
      {proposalUrl&&<div className="crm-card p-3"><p className="text-xs font-medium">Link da proposta</p><div className="mt-2 flex gap-2"><input className="crm-control min-w-0" readOnly value={proposalUrl}/><Button size="icon" aria-label="Abrir proposta" onClick={()=>window.open(proposalUrl,'_blank','noopener,noreferrer')}><ExternalLink/></Button></div></div>}
    </aside>

    <Dialog open={approvalOpen} onOpenChange={setApprovalOpen}><DialogContent><DialogHeader><DialogTitle>Solicitar aprovação comercial</DialogTitle><DialogDescription>Explique o desconto ou a margem abaixo da política.</DialogDescription></DialogHeader><textarea className="crm-control min-h-28 py-2" value={approvalReason} onChange={event=>setApprovalReason(event.target.value)} placeholder="Motivo obrigatório"/><DialogFooter><Button variant="outline" onClick={()=>setApprovalOpen(false)}>Cancelar</Button><Button disabled={pending||approvalReason.trim().length<5} onClick={()=>quote&&run(()=>requestQuoteApproval({quote_id:quote.id,reason:approvalReason}),'Aprovação solicitada.',()=>{setApprovalOpen(false);setApprovalReason('')})}>Enviar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(decision)} onOpenChange={open=>!open&&setDecision(null)}><DialogContent><DialogHeader><DialogTitle>{decision?.approve?'Aprovar condição':'Rejeitar condição'}</DialogTitle><DialogDescription>A decisão ficará no histórico comercial e na auditoria.</DialogDescription></DialogHeader><textarea className="crm-control min-h-24 py-2" value={decisionNotes} onChange={event=>setDecisionNotes(event.target.value)} placeholder="Observação obrigatória"/><DialogFooter><Button variant="outline" onClick={()=>setDecision(null)}>Cancelar</Button><Button disabled={pending||decisionNotes.trim().length<2} onClick={()=>decision&&run(()=>decideQuoteApproval({approval_id:decision.id,approve:decision.approve,notes:decisionNotes}),decision.approve?'Condição aprovada.':'Condição rejeitada.',()=>setDecision(null))}>Confirmar</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={versionOpen} onOpenChange={setVersionOpen}><DialogContent><DialogHeader><DialogTitle>Gerar nova versão</DialogTitle><DialogDescription>A versão enviada continuará imutável. Os dados atuais serão copiados para um novo rascunho.</DialogDescription></DialogHeader><Field label="Nova validade"><input type="date" className="crm-control" value={newValidity} onChange={event=>setNewValidity(event.target.value)}/></Field><DialogFooter><Button variant="outline" onClick={()=>setVersionOpen(false)}>Cancelar</Button><Button disabled={pending||!newValidity} onClick={()=>quote&&run(()=>createQuoteVersion(quote.id,newValidity),'Nova versão criada.',()=>setVersionOpen(false))}>Criar versão</Button></DialogFooter></DialogContent></Dialog>
  </div>
}

function Field({label,children,className}:{label:string;children:React.ReactNode;className?:string}){return <label className={`block min-w-0 text-xs text-muted ${className??''}`}>{label}<div className="mt-1 min-w-0">{children}</div></label>}
function NumberField({label,value,onChange,integer=false,disabled=false}:{label:string;value:number;onChange:(value:number)=>void;integer?:boolean;disabled?:boolean}){return <Field label={label}><input type="number" min="0" step={integer?1:0.01} disabled={disabled} className="crm-control" value={value} onChange={event=>onChange(Number(event.target.value))}/></Field>}
function MoneyRow({label,value,strong=false}:{label:string;value:number;strong?:boolean}){return <div className="flex items-center justify-between gap-3 text-sm"><span className="text-muted">{label}</span><span className={strong?'text-lg font-semibold':'font-medium'}>{formatBRL(value)}</span></div>}
function selectedTerm(terms:PaymentTermTemplate[],id:string){return terms.find(term=>term.id===id)}
function parseGrade(value:string){return value.split(',').map((part,position)=>{const [size,quantity]=part.split(':');return{size:(size??'').trim(),quantity:Number(quantity),position}}).filter(entry=>entry.size&&Number.isInteger(entry.quantity)&&entry.quantity>0)}
function fromItem(item:QuoteItem):DraftItem{const source=String(item.cost_source)==='auto'?'calculated':item.cost_source;return{description:item.description,product_type:item.product_type??'',model:item.model??'',fabric_id:item.fabric_id,fabric_name_snapshot:item.fabric_name_snapshot??'',color:item.color??'',customization_type:item.customization_type,quantity:Number(item.quantity),unit_price:Number(item.unit_price),unit_cost:Number(item.unit_cost),cost_source:source,discount_amount:Number(item.discount_amount),notes:item.notes??'',position:item.position,sizes:(item.sizes??[]).map(size=>({size:size.size,quantity:Number(size.quantity),position:size.position}))}}
