import assert from 'node:assert/strict'
import test from 'node:test'
import { addBusinessDays, averageCycleDays, calculateScore, conversionRate, effectiveTemperature, opportunityHealth, targetProgress, temperatureForScore, weightedForecast } from './commercial-intelligence.ts'

const rules=[
  {code:'quantity_30',name:'30+',points:5,active:true,exclusiveGroup:'quantity',threshold:30},{code:'quantity_100',name:'100+',points:15,active:true,exclusiveGroup:'quantity',threshold:100},{code:'quantity_300',name:'300+',points:25,active:true,exclusiveGroup:'quantity',threshold:300},
  {code:'desired_date',name:'Prazo',points:10,active:true},{code:'stage_negotiation',name:'Negociação',points:15,active:true},{code:'inactive_7',name:'7 dias',points:-5,active:true,exclusiveGroup:'inactivity',threshold:7},{code:'inactive_30',name:'30 dias',points:-20,active:true,exclusiveGroup:'inactivity',threshold:30},{code:'without_next_action',name:'Sem ação',points:-10,active:true},{code:'overdue_task',name:'Vencida',points:-5,active:true},
]
test('score usa faixas exclusivas e explica bônus e penalidades',()=>{const result=calculateScore({company:false,phone:false,email:false,quantity:320,desiredDate:true,stage:'negotiation',existingCustomer:false,hasOrders:false,inactivityDays:8,recentActivity:false,hasFutureTask:false,hasOverdueTask:true},rules);assert.equal(result.score,30);assert.deepEqual(result.breakdown.map((x)=>x.code),['quantity_300','desired_date','stage_negotiation','inactive_7','without_next_action','overdue_task'])})
test('temperatura calculada e override permanecem separados',()=>{assert.equal(temperatureForScore(30),'cold');assert.equal(temperatureForScore(31),'warm');assert.equal(temperatureForScore(61),'hot');assert.equal(effectiveTemperature('hot','cold'),'cold')})
test('saúde considera atraso, inatividade, ausência de ação e prazo vencido',()=>{assert.equal(opportunityHealth({status:'open',hasOverdueTask:true,inactivityDays:1,staleDays:7,hasFutureTask:true,today:'2026-09-08'}),'critical');assert.equal(opportunityHealth({status:'open',hasOverdueTask:false,inactivityDays:8,staleDays:7,hasFutureTask:true,today:'2026-09-08'}),'attention')})
test('dias úteis pulam fim de semana, feriado, mês e ano',()=>{const holidays=new Set(['2027-01-01']);assert.equal(addBusinessDays(new Date('2026-12-31T12:00:00-03:00'),1,holidays).toISOString().slice(0,10),'2027-01-04')})
test('forecast, meta, conversão e ciclo médio são determinísticos',()=>{assert.equal(weightedForecast([{value:10000,probability:75},{value:5000,probability:20}]),8500);assert.deepEqual(targetProgress(63000,100000),{won:63000,gap:37000,percent:63});assert.equal(conversionRate(14,11),56);assert.equal(averageCycleDays([{createdAt:'2026-09-01T00:00:00Z',wonAt:'2026-09-11T00:00:00Z'}]),10)})
