import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
const migration=readFileSync(new URL('../../../../supabase/migrations/202609080003_quotes_proposals.sql',import.meta.url),'utf8')
const completion=readFileSync(new URL('../../../../supabase/migrations/202609090004_quote_professional_completion.sql',import.meta.url),'utf8')
const combined=`${migration}\n${completion}`
const actions=readFileSync(new URL('../../../app/crm/orcamentos/actions.ts',import.meta.url),'utf8')
const publicActions=readFileSync(new URL('../../../app/proposta/actions.ts',import.meta.url),'utf8')
const commercialActions=readFileSync(new URL('../../../app/crm/intelligence-actions.ts',import.meta.url),'utf8')
const paymentManagement=readFileSync(new URL('../../../../supabase/migrations/202609090001_payment_term_management.sql',import.meta.url),'utf8')
const lastFunction=(name)=>[...combined.matchAll(new RegExp(`CREATE OR REPLACE FUNCTION public\\.${name}[\\s\\S]*?END \\$\\$;`,'g'))].at(-1)?.[0]??''
test('RLS protege tabelas internas e anon acessa apenas RPC pública',()=>{for(const table of ['quotes','quote_versions','quote_items','quote_item_sizes','payment_term_templates','discount_approvals','proposal_access_tokens'])assert.match(migration,new RegExp(`ALTER TABLE public\\.%I ENABLE ROW LEVEL SECURITY|ALTER TABLE public\\.${table} ENABLE ROW LEVEL SECURITY`));assert.match(migration,/REVOKE ALL ON public\.%I FROM PUBLIC,anon,authenticated/);assert.match(migration,/GRANT EXECUTE ON FUNCTION public\.get_public_proposal[\s\S]*TO anon,authenticated/)})
test('token é aleatório, armazenado como hash e DTO não contém custo ou margem',()=>{assert.match(migration,/gen_random_bytes\(32\)/);assert.match(migration,/digest\(raw_token,'sha256'\)/);const body=lastFunction('get_public_proposal');assert.doesNotMatch(body,/'estimated_cost'|'margin_percent'|'markup'|'internal_notes'|'discount_approvals'/)})
test('conversão usa lock, vínculo único, recebíveis e nenhum pagamento',()=>{const body=lastFunction('convert_quote_to_order');assert.match(body,/FOR UPDATE/);assert.match(migration,/pedidos_source_quote_unique_idx/);assert.match(body,/INSERT INTO public\.accounts_receivable/);assert.match(body,/receivable allocation mismatch/);assert.doesNotMatch(body,/INSERT INTO public\.payments|EXCEPTION WHEN unique_violation/)})
test('schemas e actions bloqueiam mass assignment',()=>{assert.match(actions,/quoteDraftSchema\.safeParse/);assert.match(actions,/requirePermission\(id\?'quotes\.update':'quotes\.create'\)/);for(const field of ['estimated_cost','estimated_profit','margin_percent','markup','approved_at','converted_order_id'])assert.doesNotMatch(publicActions,new RegExp(field))})
test('replay e respostas públicas validam estado, versão, validade e motivo',()=>{const body=lastFunction('respond_to_proposal');assert.match(body,/q\.current_version_id<>v\.id/);assert.match(body,/v\.valid_until</);assert.match(body,/q\.status NOT IN\('sent','viewed'\)/);assert.match(body,/p_action IN\('request_change','reject'\)/)})
test('processamento diário reutilizado alerta e expira propostas',()=>{const body=lastFunction('run_commercial_daily_check');assert.match(body,/quote_expiring/);assert.match(body,/quote\.expired/);assert.match(body,/status='expired'/);assert.match(body,/crm_execute_automation/)})
test('helpers privilegiados não ficam executáveis pelo cliente',()=>{assert.match(migration,/REVOKE ALL ON FUNCTION public\.quote_move_stage[\s\S]*public\.run_commercial_daily_check\(\) FROM PUBLIC,anon,authenticated/);assert.match(migration,/GRANT EXECUTE ON FUNCTION public\.run_commercial_daily_check\(\) TO service_role/)})
test('eventos comerciais e aprovações ficam auditáveis',()=>{for(const event of ['quote.created','quote.updated','quote.version_created','quote.sent','quote.viewed','quote.expired','quote.converted','discount_approval.requested','discount_approval.approved','discount_approval.rejected'])assert.ok(migration.includes(`'${event}'`),event);const response=lastFunction('respond_to_proposal');assert.match(response,/'quote\.'\|\|CASE p_action[\s\S]*'approved'[\s\S]*'rejected'[\s\S]*'change_requested'/)})
test('parcelas estruturadas são validadas antes de gerar recebíveis',()=>{assert.match(migration,/payment_term_rules_valid_check/);assert.match(migration,/abs\(total_percent-100\)<0\.01/);assert.match(lastFunction('convert_quote_to_order'),/payment_term_rules_valid\(v\.payment_terms_snapshot->'rules'\)/)})
test('edições invalidam aprovações e a renovação do link preserva a versão enviada',()=>{const save=lastFunction('save_quote_draft');const send=lastFunction('send_quote_version');assert.match(save,/status IN\('pending','approved'\)/);assert.match(save,/SET status='cancelled'/);assert.match(send,/first_send:=v\.sent_at IS NULL/);assert.match(send,/IF first_send THEN[\s\S]*UPDATE public\.quote_versions SET status='sent',sent_at=now\(\)/);assert.match(send,/ELSE[\s\S]*UPDATE public\.quotes SET updated_at=now\(\)/)})
test('configurações comerciais preservam o retorno e o recálculo do Lote 6',()=>{const save=lastFunction('save_commercial_settings');assert.match(save,/RETURNS jsonb/);assert.match(save,/crm_recalculate_score_internal/);assert.match(save,/RETURN to_jsonb\(saved\)/);assert.doesNotMatch(save,/RETURNS void/)})
test('gestão de condições de pagamento exige administração e RLS específica',()=>{assert.match(commercialActions,/function savePaymentTerm[\s\S]*requireCommercialAdmin\(\)/);assert.match(commercialActions,/installments\.reduce[\s\S]*100/);assert.match(paymentManagement,/GRANT SELECT, INSERT, UPDATE ON public\.payment_term_templates TO authenticated/);assert.match(paymentManagement,/CREATE POLICY payment_terms_insert[\s\S]*settings\.manage[\s\S]*crm\.delete/);assert.match(paymentManagement,/CREATE POLICY payment_terms_update[\s\S]*WITH CHECK/)})
test('conclusão agrega métricas no banco e mantém resposta aprovada legível sem replay',()=>{assert.match(completion,/get_quote_dashboard_stats[\s\S]*count\(\*\)[\s\S]*sum\(total_amount\)/);assert.match(lastFunction('get_public_proposal'),/status IN\('active','used'\)/);assert.match(lastFunction('get_public_proposal'),/'can_respond',t\.status='active'/);assert.match(lastFunction('approve_quote_version'),/respond_to_proposal\(p_token,'approve'/)})
test('nova versão e duplicação preservam snapshots e revogam links antigos',()=>{const version=lastFunction('create_quote_version');assert.match(version,/INSERT INTO public\.quote_versions/);assert.match(version,/INSERT INTO public\.quote_items/);assert.match(version,/INSERT INTO public\.quote_item_sizes/);assert.match(version,/status='revoked'/);assert.match(lastFunction('duplicate_quote'),/save_quote_draft\(NULL,payload,items\)/)})
test('fontes de custo seguem o domínio central solicitado',()=>{assert.match(completion,/cost_source IN\('manual','calculated','catalog','historical'\)/);assert.doesNotMatch(completion,/cost_source IN\([^)]*'auto'/)})
