'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { requireAnyPermission, requirePermission } from '@/lib/auth/require-user'
import { automationRulesSchema, commercialSettingsSchema, reactivationTasksSchema, savedViewSchema, scoreRulesSchema, targetSchema, temperatureOverrideSchema, winOpportunitySchema } from '@/lib/schemas/commercial'
import { safeDatabaseError } from '@/lib/security/errors'
import { createServerSupabaseClient } from '@/lib/supabase/server'

type Result<T=undefined>={success:true;data?:T}|{success:false;error:string}
const fail=(error:unknown,message:string):Result=>({success:false,error:safeDatabaseError(error,message,{action:'crm.commercial-intelligence'})})
const refresh=()=>{revalidatePath('/crm');revalidatePath('/crm/funil');revalidatePath('/crm/analytics');revalidatePath('/crm/reativacao');revalidatePath('/configuracoes/comercial')}
async function requireCommercialAdmin(){return requireAnyPermission(['settings.manage','crm.delete'])}

export async function saveCommercialSettings(input:unknown):Promise<Result>{await requireCommercialAdmin();const parsed=commercialSettingsSchema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Configurações inválidas.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('save_commercial_settings',{p_settings:parsed.data});if(error)return fail(error,'Não foi possível salvar as configurações.');refresh();return{success:true}}
export async function saveScoreRules(input:unknown):Promise<Result>{await requireCommercialAdmin();const parsed=scoreRulesSchema.safeParse(input);if(!parsed.success)return{success:false,error:'Regras de score inválidas.'};const supabase=await createServerSupabaseClient();for(const item of parsed.data){const {error}=await supabase.from('scoring_rules').update({points:item.points,active:item.active}).eq('id',item.id);if(error)return fail(error,'Não foi possível salvar o score.')}const {error}=await supabase.rpc('run_commercial_daily_check_now');if(error)return fail(error,'Regras salvas, mas o score não pôde ser recalculado.');refresh();return{success:true}}
export async function saveAutomationRules(input:unknown):Promise<Result>{await requireCommercialAdmin();const parsed=automationRulesSchema.safeParse(input);if(!parsed.success)return{success:false,error:'Automações inválidas.'};const supabase=await createServerSupabaseClient();for(const item of parsed.data){const {error}=await supabase.from('automation_rules').update({active:item.active}).eq('id',item.id);if(error)return fail(error,'Não foi possível salvar as automações.')}refresh();return{success:true}}
export async function createSalesTarget(input:unknown):Promise<Result>{const context=await requireCommercialAdmin();const parsed=targetSchema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Meta inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.from('sales_targets').insert({...parsed.data,team_scope:parsed.data.user_id?'individual':'company',period_type:'custom',created_by:context.user.id});if(error)return fail(error,'Não foi possível criar a meta.');refresh();return{success:true}}
export async function updateCommercialLookup(input:unknown):Promise<Result>{await requireCommercialAdmin();const schema=z.object({table:z.enum(['pipeline_stages','lead_sources','loss_reasons']),id:z.string().uuid(),name:z.string().trim().min(2).max(100),active:z.boolean(),position:z.coerce.number().int().min(0).max(999),probability:z.coerce.number().int().min(0).max(100).optional()}).strict();const parsed=schema.safeParse(input);if(!parsed.success)return{success:false,error:'Cadastro inválido.'};const {table,id,...values}=parsed.data;const supabase=await createServerSupabaseClient();const update:Record<string,unknown>={name:values.name,active:values.active,position:values.position};if(table==='pipeline_stages')update.probability=values.probability;const {error}=await supabase.from(table).update(update).eq('id',id);if(error)return fail(error,'Não foi possível atualizar o cadastro.');refresh();return{success:true}}
export async function reorderCommercialLookups(input:unknown):Promise<Result>{await requireCommercialAdmin();const schema=z.object({table:z.enum(['pipeline_stages','lead_sources','loss_reasons']),ids:z.array(z.string().uuid()).min(1).max(100)}).strict();const parsed=schema.safeParse(input);if(!parsed.success||new Set(parsed.data.ids).size!==parsed.data.ids.length)return{success:false,error:'Ordem inválida.'};const supabase=await createServerSupabaseClient();for(const [position,id] of parsed.data.ids.entries()){const {error}=await supabase.from(parsed.data.table).update({position}).eq('id',id);if(error)return fail(error,'Não foi possível salvar a ordem.')}refresh();return{success:true}}
export async function savePaymentTerm(input:unknown):Promise<Result>{await requireCommercialAdmin();const installment=z.object({label:z.string().trim().min(1).max(60),percent:z.coerce.number().positive().max(100),due_type:z.enum(['order_date','days_after_order','delivery_date']),days:z.coerce.number().int().min(0).max(3650).optional()}).strict();const schema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(2).max(100),description:z.string().trim().max(300).nullable(),active:z.boolean(),installments:z.array(installment).min(1).max(12)}).strict().refine(value=>Math.abs(value.installments.reduce((sum,item)=>sum+item.percent,0)-100)<0.01,{message:'As parcelas devem somar 100%.'}).refine(value=>value.installments.every(item=>item.due_type==='days_after_order'||item.days==null),{message:'Dias só podem ser usados após o pedido.'});const parsed=schema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Condição de pagamento inválida.'};const {id,installments,...values}=parsed.data;const supabase=await createServerSupabaseClient();const payload={...values,rules:{installments}};const result=id?await supabase.from('payment_term_templates').update(payload).eq('id',id):await supabase.from('payment_term_templates').insert(payload);if(result.error)return fail(result.error,'Não foi possível salvar a condição de pagamento.');refresh();return{success:true}}
export async function createCommercialLookup(input:unknown):Promise<Result>{await requireCommercialAdmin();const schema=z.object({table:z.enum(['pipeline_stages','lead_sources','loss_reasons']),name:z.string().trim().min(2).max(100),position:z.coerce.number().int().min(0).max(999),probability:z.coerce.number().int().min(0).max(100).optional(),pipeline_id:z.string().uuid().optional()}).strict();const parsed=schema.safeParse(input);if(!parsed.success||parsed.data.table==='pipeline_stages'&&!parsed.data.pipeline_id)return{success:false,error:'Cadastro inválido.'};const supabase=await createServerSupabaseClient();const code=`custom_${Date.now().toString(36)}`;const common={code,name:parsed.data.name,position:parsed.data.position,active:true};const payload=parsed.data.table==='pipeline_stages'?{...common,pipeline_id:parsed.data.pipeline_id,probability:parsed.data.probability??0,is_won:false,is_lost:false}:common;const {error}=await supabase.from(parsed.data.table).insert(payload);if(error)return fail(error,'Não foi possível criar o cadastro.');refresh();return{success:true}}
export async function createReactivationTasks(input:unknown):Promise<Result<{count:number}>>{await requirePermission('crm.create');const parsed=reactivationTasksSchema.safeParse(input);if(!parsed.success)return{success:false,error:'Revise os clientes, responsável e vencimento.'};const supabase=await createServerSupabaseClient();const {data,error}=await supabase.rpc('create_reactivation_tasks',{p_customer_ids:parsed.data.customer_ids,p_assigned_user_id:parsed.data.assigned_user_id,p_due_at:parsed.data.due_at,p_title:parsed.data.title});if(error)return fail(error,'Não foi possível criar as tarefas.') as Result<{count:number}>;revalidatePath('/crm/reativacao');revalidatePath('/tarefas');return{success:true,data:{count:Number(data)}}}
export async function saveCrmView(input:unknown):Promise<Result<{id:string}>>{await requirePermission('crm.view');const parsed=savedViewSchema.safeParse(input);if(!parsed.success)return{success:false,error:'Visão inválida.'};const supabase=await createServerSupabaseClient();const {data,error}=await supabase.rpc('save_crm_view',{p_module:parsed.data.module,p_name:parsed.data.name,p_filters:parsed.data.filters,p_is_default:parsed.data.is_default});if(error)return fail(error,'Não foi possível salvar a visão.') as Result<{id:string}>;refresh();return{success:true,data:{id:String(data)}}}
export async function markCommercialNotificationRead(id:string):Promise<Result>{await requirePermission('crm.view');const parsed=z.string().uuid().safeParse(id);if(!parsed.success)return{success:false,error:'Notificação inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('mark_notification_read',{p_notification_id:parsed.data});if(error)return fail(error,'Não foi possível marcar a notificação.');return{success:true}}
export async function recalculateOpportunityScore(id:string):Promise<Result>{await requireCommercialAdmin();const parsed=z.string().uuid().safeParse(id);if(!parsed.success)return{success:false,error:'Oportunidade inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('recalculate_opportunity_score',{p_opportunity_id:parsed.data});if(error)return fail(error,'Não foi possível recalcular o score.');revalidatePath(`/crm/oportunidades/${id}`);return{success:true}}
export async function setTemperatureOverride(input:unknown):Promise<Result>{await requirePermission('crm.update');const parsed=temperatureOverrideSchema.safeParse(input);if(!parsed.success)return{success:false,error:'Temperatura inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('set_opportunity_temperature_override',{p_opportunity_id:parsed.data.opportunity_id,p_temperature:parsed.data.temperature});if(error)return fail(error,'Não foi possível alterar a temperatura.');revalidatePath(`/crm/oportunidades/${parsed.data.opportunity_id}`);revalidatePath('/crm/funil');return{success:true}}
export async function winOpportunity(input:unknown):Promise<Result>{await requirePermission('crm.update');const parsed=winOpportunitySchema.safeParse(input);if(!parsed.success)return{success:false,error:'Informe o valor final e uma data de fechamento válida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('win_opportunity',{p_opportunity_id:parsed.data.opportunity_id,p_final_value:parsed.data.final_value,p_closed_at:parsed.data.closed_at,p_notes:parsed.data.notes,p_expected_stage_entered_at:parsed.data.expected_stage_entered_at});if(error)return fail(error,'Não foi possível marcar a oportunidade como ganha.');refresh();revalidatePath(`/crm/oportunidades/${parsed.data.opportunity_id}`);return{success:true}}
