import { z } from 'zod'

export const commercialSettingsSchema=z.object({stale_opportunity_days:z.coerce.number().int().min(1).max(365),follow_up_default_days:z.coerce.number().int().min(1).max(30),second_follow_up_days:z.coerce.number().int().min(2).max(60),third_alert_days:z.coerce.number().int().min(3).max(90),warm_lead_threshold:z.coerce.number().int().min(1).max(99),hot_lead_threshold:z.coerce.number().int().min(2).max(100),use_business_days:z.boolean(),minimum_margin_percent:z.coerce.number().min(0).max(100),default_quote_validity_days:z.coerce.number().int().min(1).max(180),discount_limits:z.object({salesperson:z.coerce.number().min(0).max(100),commercial:z.coerce.number().min(0).max(100),manager:z.coerce.number().min(0).max(100),administrator:z.coerce.number().min(0).max(100)}).strict(),require_margin_approval:z.boolean()}).strict().refine(v=>v.hot_lead_threshold>v.warm_lead_threshold,{message:'A faixa quente deve ser maior que a morna.'})
export const scoreRulesSchema=z.array(z.object({id:z.string().uuid(),points:z.coerce.number().int().min(-100).max(100),active:z.boolean()}).strict()).min(1).max(50)
export const automationRulesSchema=z.array(z.object({id:z.string().uuid(),active:z.boolean()}).strict()).max(50)
export const targetSchema=z.object({user_id:z.string().uuid().nullable(),target_type:z.enum(['revenue_won','opportunities_won']),period_start:z.iso.date(),period_end:z.iso.date(),target_value:z.coerce.number().positive()}).strict().refine(v=>v.period_end>=v.period_start,{message:'Período inválido.'})
export const reactivationTasksSchema=z.object({customer_ids:z.array(z.string().uuid()).min(1).max(100),assigned_user_id:z.string().uuid(),due_at:z.iso.datetime(),title:z.string().trim().min(2).max(160)}).strict()
export const savedViewSchema=z.object({module:z.enum(['crm','crm_analytics','reactivation']),name:z.string().trim().min(2).max(80),filters:z.record(z.string(),z.string()),is_default:z.boolean()}).strict()
export const winOpportunitySchema=z.object({opportunity_id:z.string().uuid(),final_value:z.coerce.number().min(0),closed_at:z.iso.datetime(),notes:z.string().trim().max(2000).nullable(),expected_stage_entered_at:z.iso.datetime()}).strict()
export const temperatureOverrideSchema=z.object({opportunity_id:z.string().uuid(),temperature:z.enum(['cold','warm','hot']).nullable()}).strict()
