'use client'

import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CircleDollarSign, Clock3, Percent, Receipt, TrendingUp } from 'lucide-react'
import { formatBRL } from '@/lib/utils'
import type { CommercialAnalyticsData, ForecastData } from '@/types/commercial'
import type { QuoteDashboardStats } from '@/types/quotes'
import { EmptyState, MetricCard, SectionCard } from './CrmUi'

const compactCurrency=(value:number)=>new Intl.NumberFormat('pt-BR',{notation:'compact',style:'currency',currency:'BRL',maximumFractionDigits:1}).format(value)

export function CommercialAnalytics({data,forecast,quotes}:{data:CommercialAnalyticsData;forecast:ForecastData;quotes:QuoteDashboardStats}){
  const change=data.comparison.change_percent
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
      <MetricCard label="Receita ganha" value={formatBRL(Number(data.summary.won_value))} icon={<CircleDollarSign size={18}/>} change={change}/>
      <MetricCard label="Conversão" value={data.summary.conversion_rate==null?'—':`${data.summary.conversion_rate}%`} icon={<Percent size={18}/>} detail={`${data.summary.won} ganhos`}/>
      <MetricCard label="Ticket médio" value={data.summary.avg_ticket==null?'—':formatBRL(Number(data.summary.avg_ticket))} icon={<Receipt size={18}/>} />
      <MetricCard label="Ciclo médio" value={data.summary.avg_cycle_days==null?'—':`${data.summary.avg_cycle_days} dias`} icon={<Clock3 size={18}/>} />
      <MetricCard label="Pipeline ponderado" value={formatBRL(Number(forecast.pipeline_weighted))} icon={<TrendingUp size={18}/>} tone="success"/>
    </div>

    <SectionCard title="Orçamentos e propostas" description="Indicadores agregados no banco para o período selecionado."><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5"><MetricCard compact label="Orçamentos criados" value={quotes.created}/><MetricCard compact label="Propostas enviadas" value={quotes.sent} detail={formatBRL(quotes.sentValue)}/><MetricCard compact label="Aguardando retorno" value={quotes.waiting} detail={formatBRL(quotes.waitingValue)} tone="warning"/><MetricCard compact label="Aprovadas" value={quotes.approved} detail={formatBRL(quotes.approvedValue)} tone="success"/><MetricCard compact label="Taxa de aprovação" value={`${quotes.approvalRate}%`} detail={`Margem média ${quotes.averageMargin}%`}/><MetricCard compact label="Descontos em aprovação" value={quotes.pendingApprovals} detail={formatBRL(quotes.pendingApprovalValue)} tone={quotes.pendingApprovals?'warning':'neutral'}/></div></SectionCard>

    <div className="grid gap-5 xl:grid-cols-2">
      <SectionCard title="Receita ganha ao longo do tempo" description="Valores fechados no período selecionado."><ChartBox empty={!data.revenue_trend.length}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.revenue_trend} margin={{top:12,right:10,left:4,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border-subtle)"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:'var(--fg-muted)',fontSize:11}}/><YAxis width={66} axisLine={false} tickLine={false} tickFormatter={compactCurrency} tick={{fill:'var(--fg-muted)',fontSize:11}}/><Tooltip cursor={{fill:'var(--surface-subtle)'}} contentStyle={{background:'var(--tooltip-bg)',border:'1px solid var(--tooltip-border)',borderRadius:10}} formatter={(value)=>[formatBRL(Number(value)),'Receita']}/><Bar dataKey="value" fill="var(--brand-green)" radius={[5,5,0,0]} maxBarSize={42}/></BarChart></ResponsiveContainer></ChartBox></SectionCard>
      <SectionCard title="Funil comercial" description="Volume alcançado e conversão entre etapas."><div className="space-y-3 p-5">{data.funnel.map((item,index)=>{const max=Math.max(...data.funnel.map(x=>x.reached),1);const conversion=index===0?100:data.funnel[index-1].reached?Math.round(item.reached/data.funnel[index-1].reached*100):0;return <div key={item.id}><div className="mb-1.5 flex items-center justify-between gap-3 text-sm"><span className="truncate font-medium">{item.name}</span><span className="shrink-0 text-xs text-muted">{item.reached} · {conversion}%</span></div><div className="h-7 overflow-hidden rounded-md bg-surface-hover"><div className="flex h-full min-w-8 items-center rounded-md bg-green-600/80 px-2 text-[11px] font-medium text-white transition-all" style={{width:`${Math.max(8,item.reached/max*100)}%`}}>{item.count}</div></div></div>})}{!data.funnel.length&&<EmptyState title="Sem dados no funil" description="Não houve movimentação no período selecionado."/>}</div></SectionCard>
    </div>

    <div className="grid gap-5 xl:grid-cols-2">
      <SectionCard title="Conversão por origem" description="Canais com maior eficiência comercial."><div className="space-y-3 p-5">{data.sources.map(item=><div key={item.id}><div className="mb-1.5 flex justify-between text-sm"><span>{item.name}</span><strong>{item.conversion_rate??0}%</strong></div><div className="h-2 rounded-full bg-surface-hover"><div className="h-full rounded-full bg-blue-500" style={{width:`${Math.min(100,Number(item.conversion_rate??0))}%`}}/></div><p className="mt-1 text-[11px] text-muted">{item.won} ganhos · {formatBRL(Number(item.won_value))}</p></div>)}{!data.sources.length&&<EmptyState title="Sem origens no período" description="A conversão aparecerá quando houver oportunidades com origem."/>}</div></SectionCard>
      <SectionCard title="Performance por vendedor" description="Receita e pipeline por responsável."><ChartBox empty={!data.sellers.length}><ResponsiveContainer width="100%" height="100%"><BarChart data={data.sellers} margin={{top:12,right:10,left:4,bottom:0}}><CartesianGrid vertical={false} stroke="var(--border-subtle)"/><XAxis dataKey="full_name" axisLine={false} tickLine={false} tick={{fill:'var(--fg-muted)',fontSize:11}}/><YAxis width={66} axisLine={false} tickLine={false} tickFormatter={compactCurrency} tick={{fill:'var(--fg-muted)',fontSize:11}}/><Tooltip contentStyle={{background:'var(--tooltip-bg)',border:'1px solid var(--tooltip-border)',borderRadius:10}} formatter={(value,name)=>[formatBRL(Number(value)),name==='won_value'?'Receita':'Pipeline']}/><Bar dataKey="won_value" fill="var(--brand-green)" radius={[4,4,0,0]} maxBarSize={28}/><Bar dataKey="pipeline" fill="var(--crm-info)" radius={[4,4,0,0]} maxBarSize={28}/></BarChart></ResponsiveContainer></ChartBox></SectionCard>
    </div>

    <AnalyticsTable title="Tempo por etapa" headers={['Etapa','Atuais','Valor','Paradas','Média','Mediana']} rows={data.funnel.map(item=>[item.name,item.count,formatBRL(Number(item.value)),item.stale,`${item.avg_days??'—'} dias`,`${item.median_days??'—'} dias`])} duration={data.funnel.map(item=>Number(item.avg_days??0))}/>
    <AnalyticsTable title="Desempenho detalhado" headers={['Vendedor','Receita','Conversão','Ticket','Ciclo','Atrasos']} rows={data.sellers.map(item=>[item.full_name,formatBRL(Number(item.won_value)),item.conversion_rate==null?'—':`${item.conversion_rate}%`,item.avg_ticket==null?'—':formatBRL(Number(item.avg_ticket)),item.avg_cycle_days==null?'—':`${item.avg_cycle_days} dias`,item.overdue_tasks])}/>
    <div className="grid gap-5 xl:grid-cols-2"><AnalyticsTable title="Origens" headers={['Origem','Leads','Oportunidades','Ganhas','Receita']} rows={data.sources.map(item=>[item.name,item.leads,item.opportunities,item.won,formatBRL(Number(item.won_value))])}/><AnalyticsTable title="Perdas e concorrentes" headers={['Motivo / concorrente','Qtde.','% perdas','Valor']} rows={[...data.losses,...data.competitors].map(item=>[item.name,item.count,data.summary.lost?`${Math.round(item.count/data.summary.lost*1000)/10}%`:'—',formatBRL(Number(item.lost_value))])}/></div>
    <p className="text-xs text-muted">{data.method}</p>
  </div>
}

function ChartBox({children,empty}:{children:React.ReactNode;empty:boolean}){return <div className="h-80 p-4">{empty?<EmptyState title="Sem receita no período" description="Os fechamentos ganhos aparecerão neste gráfico."/>:children}</div>}
function AnalyticsTable({title,headers,rows,duration}:{title:string;headers:string[];rows:Array<Array<string|number|null>>;duration?:number[]}){const max=Math.max(...(duration??[0]),1);return <SectionCard title={title}><div className="overflow-x-auto"><table className="crm-table"><thead><tr>{headers.map(header=><th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((value,column)=><td key={column} className="whitespace-nowrap">{column===0&&duration?<div className="min-w-44"><span>{value??'—'}</span><div className="mt-1.5 h-1.5 rounded-full bg-surface-hover"><div className="h-full rounded-full bg-green-600/70" style={{width:`${duration[index]/max*100}%`}}/></div></div>:value??'—'}</td>)}</tr>)}{!rows.length&&<tr><td colSpan={headers.length} className="p-0"><EmptyState title="Sem dados no período" description="Ajuste os filtros ou aguarde novas movimentações."/></td></tr>}</tbody></table></div></SectionCard>}
