'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import { Loader2, Plus } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { addContact, createOpportunity } from '@/app/crm/actions'
import { usePermission } from '@/components/providers/AuthorizationProvider'
import { formatBRL, formatDate } from '@/lib/utils'
import type { CrmActivity, CrmContact, CrmProfile, CrmTask, LeadSource, Opportunity, PipelineStage } from '@/types/crm'

const control='w-full rounded-lg border bg-transparent px-3 py-2 text-sm'
export function CustomerCrmSection({customerId,contacts,opportunities,activities,tasks,pipelineId,stages,profiles,sources}:{customerId:string;contacts:CrmContact[];opportunities:Opportunity[];activities:CrmActivity[];tasks:CrmTask[];pipelineId:string;stages:PipelineStage[];profiles:CrmProfile[];sources:LeadSource[]}){const canCreate=usePermission('crm.create');const [contactOpen,setContactOpen]=useState(false);const [opportunityOpen,setOpportunityOpen]=useState(false);return <section className="space-y-4"><div className="flex justify-between items-center"><h3 className="font-semibold">Relacionamento comercial</h3>{canCreate&&<div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setContactOpen(true)}><Plus/>Contato</Button><Button size="sm" onClick={()=>setOpportunityOpen(true)}><Plus/>Oportunidade</Button></div>}</div><div className="grid lg:grid-cols-2 gap-4"><Panel title="Contatos">{contacts.map((c)=><div key={c.id} className="border-t first:border-0 py-2 text-sm"><strong>{c.name}</strong>{c.is_primary&&<span className="ml-2 text-[10px] bg-green-500/10 text-green-600 px-2 py-0.5 rounded-full">Principal</span>}<p className="text-xs text-muted">{c.job_title} {c.whatsapp||c.phone||c.email}</p></div>)}{!contacts.length&&<Empty/>}</Panel><Panel title="Oportunidades">{opportunities.map((o)=><Link key={o.id} href={`/crm/oportunidades/${o.id}`} className="block border-t first:border-0 py-2 text-sm hover:text-green-600"><div className="flex justify-between"><strong>{o.title}</strong><span>{formatBRL(Number(o.estimated_value))}</span></div><p className="text-xs text-muted">{o.stage?.name} · {o.status}</p></Link>)}{!opportunities.length&&<Empty/>}</Panel><Panel title="Atividades recentes">{activities.map((a)=><div key={a.id} className="border-t first:border-0 py-2 text-sm"><strong>{a.title}</strong><p className="text-xs text-muted">{formatDate(a.occurred_at)} · {a.user?.full_name}</p></div>)}{!activities.length&&<Empty/>}</Panel><Panel title="Próxima ação">{tasks.slice(0,5).map((t)=><div key={t.id} className="border-t first:border-0 py-2 text-sm"><strong>{t.title}</strong><p className="text-xs text-muted">{formatDate(t.due_at)} · {t.priority}</p></div>)}{!tasks.length&&<Empty/>}</Panel></div><ContactModal open={contactOpen} onClose={()=>setContactOpen(false)} customerId={customerId}/><OpportunityModal open={opportunityOpen} onClose={()=>setOpportunityOpen(false)} customerId={customerId} pipelineId={pipelineId} stages={stages} profiles={profiles} sources={sources}/></section>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-xl border p-4" style={{background:'var(--card-bg)',borderColor:'var(--border-color)'}}><h4 className="text-sm font-semibold mb-2">{title}</h4>{children}</div>} function Empty(){return <p className="text-sm text-muted py-3">Nenhum registro.</p>}
function ContactModal({open,onClose,customerId}:{open:boolean;onClose:()=>void;customerId:string}){const router=useRouter();const [pending,startTransition]=useTransition();const [form,setForm]=useState({name:'',job_title:'',phone:'',whatsapp:'',email:'',is_primary:false,notes:''});const submit=()=>startTransition(async()=>{const result=await addContact({...form,customer_id:customerId});if(!result.success)toast.error(result.error);else{toast.success('Contato criado.');onClose();router.refresh()}});return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Novo contato</DialogTitle></DialogHeader>{(['name','job_title','phone','whatsapp','email'] as const).map((key)=><input key={key} className={control} placeholder={{name:'Nome *',job_title:'Cargo',phone:'Telefone',whatsapp:'WhatsApp',email:'E-mail'}[key]} value={String(form[key])} onChange={(e)=>setForm({...form,[key]:e.target.value})}/>)}<label className="flex gap-2 text-sm"><input type="checkbox" checked={form.is_primary} onChange={(e)=>setForm({...form,is_primary:e.target.checked})}/>Contato principal</label><Button disabled={pending||form.name.length<2} onClick={submit}>{pending&&<Loader2 className="animate-spin"/>}Salvar</Button></DialogContent></Dialog>}
function OpportunityModal({open,onClose,customerId,pipelineId,stages,profiles,sources}:{open:boolean;onClose:()=>void;customerId:string;pipelineId:string;stages:PipelineStage[];profiles:CrmProfile[];sources:LeadSource[]}){const router=useRouter();const [pending,startTransition]=useTransition();const [form,setForm]=useState({title:'',assigned_user_id:profiles[0]?.id??'',source_id:'',estimated_value:'0',estimated_quantity:'0',temperature:'warm',expected_close_date:'',desired_delivery_date:'',notes:''});const stage=stages.find((s)=>s.pipeline_id===pipelineId&&!s.is_won&&!s.is_lost);const submit=()=>startTransition(async()=>{if(!stage)return;const result=await createOpportunity({...form,customer_id:customerId,contact_id:null,pipeline_id:pipelineId,stage_id:stage.id});if(!result.success)toast.error(result.error);else router.push(`/crm/oportunidades/${result.data?.id}`)});return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Nova oportunidade</DialogTitle></DialogHeader><input className={control} placeholder="Título *" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><input className={control} type="number" min="0" placeholder="Valor estimado" value={form.estimated_value} onChange={(e)=>setForm({...form,estimated_value:e.target.value})}/><input className={control} type="number" min="0" placeholder="Quantidade" value={form.estimated_quantity} onChange={(e)=>setForm({...form,estimated_quantity:e.target.value})}/><select className={control} value={form.assigned_user_id} onChange={(e)=>setForm({...form,assigned_user_id:e.target.value})}>{profiles.map((p)=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select className={control} value={form.source_id} onChange={(e)=>setForm({...form,source_id:e.target.value})}><option value="">Origem</option>{sources.map((s)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select className={control} value={form.temperature} onChange={(e)=>setForm({...form,temperature:e.target.value})}><option value="cold">Fria</option><option value="warm">Morna</option><option value="hot">Quente</option></select><Button disabled={pending||!form.title||!form.assigned_user_id} onClick={submit}>{pending&&<Loader2 className="animate-spin"/>}Criar oportunidade</Button></DialogContent></Dialog>}
