'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState, useTransition } from 'react'
import { Archive, Check, Clock, Flame, Loader2, MessageSquarePlus, Plus, RotateCcw } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { archiveOpportunity, createTask, finishTask, moveOpportunityStage, recordActivity, reopenOpportunity, setOpportunityTags } from '@/app/crm/actions'
import { recalculateOpportunityScore, setTemperatureOverride, winOpportunity } from '@/app/crm/intelligence-actions'
import { usePermission } from '@/components/providers/AuthorizationProvider'
import { formatDate } from '@/lib/utils'
import type { CrmActivity, CrmContact, CrmTag, CrmTask, LossReason, Opportunity, PipelineStage } from '@/types/crm'

const control = 'w-full rounded-lg border bg-transparent px-3 py-2 text-sm outline-none focus:ring-1 focus:ring-green-500'

export function OpportunityWorkspace({ opportunity, activities, tasks, contacts, stages, reasons, tags, manager }: { opportunity: Opportunity; activities: CrmActivity[]; activityCount?: number; activityPage?: number; tasks: CrmTask[]; contacts: CrmContact[]; stages: PipelineStage[]; reasons: LossReason[]; tags: CrmTag[]; manager: boolean }) {
  const canCreate = usePermission('crm.create'), canUpdate = usePermission('crm.update'), canDelete = usePermission('crm.delete')
  const router = useRouter(); const [pending,startTransition] = useTransition(); const [activityOpen,setActivityOpen] = useState(false); const [taskOpen,setTaskOpen] = useState(false); const [winOpen,setWinOpen] = useState(false); const [lossReason,setLossReason] = useState(''); const [reopenReason,setReopenReason] = useState('')
  const [selectedTags,setSelectedTags] = useState((opportunity.opportunity_tags ?? []).flatMap((item) => item.tags ? [item.tags.id] : []))
  const pipelineStages = stages.filter((item) => item.pipeline_id === opportunity.pipeline_id)
  function stage(stageId: string) { const selected = pipelineStages.find((item) => item.id === stageId); if (!selected) return; if (selected.is_lost && !lossReason) { toast.error('Selecione o motivo da perda.'); return } startTransition(async () => { const result = await moveOpportunityStage({ opportunity_id: opportunity.id, stage_id: selected.id, loss_reason_id: selected.is_lost ? lossReason : null, competitor_name: null, notes: null, expected_stage_entered_at: opportunity.stage_entered_at }); if (!result.success) toast.error(result.error); else { toast.success('Etapa atualizada.'); router.refresh() } }) }
  function finish(id: string) { startTransition(async () => { const result = await finishTask(id); if (!result.success) toast.error(result.error); else { toast.success('Tarefa concluída.'); router.refresh() } }) }
  function reopen() { const target = pipelineStages.find((item) => !item.is_won && !item.is_lost); if (!target) return; startTransition(async () => { const result = await reopenOpportunity({ opportunity_id: opportunity.id, stage_id: target.id, reason: reopenReason }); if (!result.success) toast.error(result.error); else { toast.success('Oportunidade reaberta.'); router.refresh() } }) }
  function archive() { if (!confirm('Arquivar esta oportunidade?')) return; startTransition(async () => { const result = await archiveOpportunity(opportunity.id); if (!result.success) toast.error(result.error); else router.push('/crm') }) }
  function saveTags() { startTransition(async()=>{const result=await setOpportunityTags(opportunity.id,selectedTags);if(!result.success)toast.error(result.error);else{toast.success('Tags atualizadas.');router.refresh()}}) }
  return <div className="grid xl:grid-cols-[1fr_360px] gap-5">
    <section id="atividades" className="space-y-5">
      <div className="rounded-xl border p-4" style={{ background: 'var(--card-bg)', borderColor: 'var(--border-color)' }}><div className="flex flex-wrap gap-3 items-end"><label className="text-xs flex-1 min-w-52">Etapa<select disabled={!canUpdate || opportunity.status !== 'open'} className={`${control} mt-1`} value={opportunity.stage_id} onChange={(e) => stage(e.target.value)}>{pipelineStages.filter(item=>!item.is_won).map((item) => <option key={item.id} value={item.id}>{item.name} · {item.probability}%</option>)}</select></label>{pipelineStages.some((item) => item.is_lost) && opportunity.status === 'open' && <label className="text-xs flex-1 min-w-48">Motivo da perda<select className={`${control} mt-1`} value={lossReason} onChange={(e) => setLossReason(e.target.value)}><option value="">Selecione antes de mover para Perdido</option>{reasons.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}{canUpdate&&opportunity.status==='open'&&<Button onClick={()=>setWinOpen(true)}><Flame/>Marcar como ganha</Button>}{manager && ['won','lost'].includes(opportunity.status) && <><input className={`${control} max-w-64`} placeholder="Motivo da reabertura" value={reopenReason} onChange={(e) => setReopenReason(e.target.value)}/><Button variant="outline" disabled={pending || reopenReason.length < 3} onClick={reopen}><RotateCcw/>Reabrir</Button></>}{canDelete && <Button variant="destructive" onClick={archive}><Archive/>Arquivar</Button>}</div></div>
      {tags.length>0&&<div className="rounded-xl border p-4 flex flex-wrap items-center gap-2" style={{background:'var(--card-bg)',borderColor:'var(--border-color)'}}><span className="text-xs text-muted">Tags</span>{tags.map((tag)=><label key={tag.id} className="rounded-full border px-2 py-1 text-xs flex gap-1"><input disabled={!canUpdate} type="checkbox" checked={selectedTags.includes(tag.id)} onChange={(e)=>setSelectedTags((current)=>e.target.checked?[...current,tag.id]:current.filter((id)=>id!==tag.id))}/><span style={{color:tag.color}}>●</span>{tag.name}</label>)}{canUpdate&&<Button size="xs" variant="outline" onClick={saveTags}>Salvar tags</Button>}</div>}
      <div className="rounded-xl border" style={{ background: 'var(--card-bg)', borderColor: 'var(--border-color)' }}><header className="p-4 border-b flex justify-between" style={{ borderColor: 'var(--border-color)' }}><div><h2 className="font-semibold">Timeline comercial</h2><p className="text-xs text-muted">Atividades registradas pela equipe</p></div>{canCreate && <Button size="sm" onClick={() => setActivityOpen(true)}><MessageSquarePlus/>Atividade</Button>}</header><div className="p-4 space-y-4">{activities.map((activity) => <div key={activity.id} className="flex gap-3"><div className="w-8 h-8 shrink-0 rounded-full bg-green-500/10 flex items-center justify-center text-green-600"><Clock size={14}/></div><div><div className="flex flex-wrap gap-2 items-baseline"><strong className="text-sm">{activity.title}</strong><span className="text-xs text-muted">{new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(activity.occurred_at))}</span></div><p className="text-xs text-muted">{activity.user?.full_name} · {activity.type}</p>{activity.description && <p className="text-sm mt-1 whitespace-pre-wrap">{activity.description}</p>}</div></div>)}{!activities.length && <p className="text-sm text-muted text-center py-8">Nenhuma atividade registrada.</p>}</div></div>
    </section>
    <aside className="space-y-5"><ScoreCard opportunity={opportunity} canUpdate={canUpdate&&manager} pending={pending} run={startTransition}/><div className="rounded-xl border" style={{ background: 'var(--card-bg)', borderColor: 'var(--border-color)' }}><header className="p-4 border-b flex justify-between" style={{ borderColor: 'var(--border-color)' }}><h2 className="font-semibold">Próximas tarefas</h2>{canCreate && <Button size="xs" onClick={() => setTaskOpen(true)}><Plus/></Button>}</header><div className="p-3 space-y-2">{tasks.map((task) => <div key={task.id} className={`rounded-lg border p-3 ${task.status !== 'pending' ? 'opacity-60' : ''}`}><div className="flex justify-between gap-2"><strong className="text-sm">{task.title}</strong>{task.status === 'pending' && canUpdate && <Button size="icon-xs" variant="outline" onClick={() => finish(task.id)}><Check/></Button>}</div><p className="text-xs text-muted mt-1">{formatDate(task.due_at)} · {task.priority}</p></div>)}{!tasks.length && <p className="text-sm text-muted text-center py-5">Sem tarefas.</p>}<Link href="/tarefas" className="block text-xs text-center text-green-600 mt-2">Ver central de tarefas</Link></div></div></aside>
    <ActivityDialog open={activityOpen} onClose={() => setActivityOpen(false)} opportunity={opportunity} contacts={contacts}/><TaskDialog open={taskOpen} onClose={() => setTaskOpen(false)} opportunity={opportunity} contacts={contacts}/><OpportunityWinDialog open={winOpen} onClose={()=>setWinOpen(false)} opportunity={opportunity}/>{pending && <div className="fixed right-5 bottom-5 bg-green-600 text-white rounded-lg px-3 py-2 flex gap-2"><Loader2 className="animate-spin"/>Salvando</div>}
  </div>
}

function ScoreCard({opportunity,canUpdate,pending,run}:{opportunity:Opportunity;canUpdate:boolean;pending:boolean;run:React.TransitionStartFunction}){const router=useRouter();const label=opportunity.temperature==='hot'?'QUENTE':opportunity.temperature==='cold'?'FRIA':'MORNA';const save=(temperature:'cold'|'warm'|'hot'|null)=>run(async()=>{const r=await setTemperatureOverride({opportunity_id:opportunity.id,temperature});if(!r.success)toast.error(r.error);else{toast.success('Temperatura atualizada.');router.refresh()}});return <div className="rounded-xl border p-4" style={{background:'var(--card-bg)',borderColor:'var(--border-color)'}}><div className="flex justify-between"><div><p className="text-xs text-muted">Score comercial</p><strong className="text-lg">{label} — {opportunity.score} pontos</strong></div>{opportunity.temperature_override&&<span className="text-xs text-amber-600">Manual</span>}</div><details className="mt-3"><summary className="text-xs text-green-600 cursor-pointer">Por quê?</summary><ul className="mt-2 space-y-1">{(opportunity.score_breakdown??[]).map(x=><li key={x.code} className="text-xs flex justify-between"><span>{x.label}</span><strong>{x.points>0?'+':''}{x.points}</strong></li>)}</ul></details>{canUpdate&&<div className="mt-3 flex flex-wrap gap-1">{(['cold','warm','hot'] as const).map(x=><Button key={x} size="xs" variant="outline" disabled={pending} onClick={()=>save(x)}>{x==='cold'?'Fria':x==='warm'?'Morna':'Quente'}</Button>)}<Button size="xs" variant="ghost" onClick={()=>save(null)}>Automática</Button><Button size="xs" variant="ghost" onClick={()=>run(async()=>{const r=await recalculateOpportunityScore(opportunity.id);if(!r.success)toast.error(r.error);else router.refresh()})}><RotateCcw/>Recalcular</Button></div>}</div>}
function OpportunityWinDialog({open,onClose,opportunity}:{open:boolean;onClose:()=>void;opportunity:Opportunity}){const router=useRouter();const [pending,startTransition]=useTransition();const [value,setValue]=useState(String(opportunity.estimated_value));const [date,setDate]=useState('');const [notes,setNotes]=useState('');function submit(){startTransition(async()=>{const r=await winOpportunity({opportunity_id:opportunity.id,final_value:Number(value),closed_at:new Date(date).toISOString(),notes:notes||null,expected_stage_entered_at:opportunity.stage_entered_at});if(!r.success)toast.error(r.error);else{toast.success('Oportunidade ganha.');onClose();router.refresh()}})}return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Confirmar ganho</DialogTitle></DialogHeader><label className="text-xs">Valor final *<input className={`${control} mt-1`} type="number" min="0" step="0.01" value={value} onChange={e=>setValue(e.target.value)}/></label><label className="text-xs">Data do fechamento *<input className={`${control} mt-1`} type="datetime-local" max={new Date().toISOString().slice(0,16)} value={date} onChange={e=>setDate(e.target.value)}/></label><textarea className={control} placeholder="Observações" value={notes} onChange={e=>setNotes(e.target.value)}/><Button disabled={pending||!date||Number(value)<0} onClick={submit}>{pending&&<Loader2 className="animate-spin"/>}Confirmar ganho</Button></DialogContent></Dialog>}

function ActivityDialog({ open,onClose,opportunity,contacts }: { open:boolean; onClose:()=>void; opportunity:Opportunity; contacts:CrmContact[] }) { const router=useRouter(); const [pending,startTransition]=useTransition(); const [form,setForm]=useState({type:'note',title:'',description:'',contact_id:''}); const submit=()=>startTransition(async()=>{const result=await recordActivity({opportunity_id:opportunity.id,contact_id:form.contact_id||null,type:form.type,title:form.title,description:form.description||null,occurred_at:null});if(!result.success)toast.error(result.error);else{toast.success('Atividade registrada.');onClose();router.refresh()}}); return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Registrar atividade</DialogTitle></DialogHeader><select className={control} value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option value="note">Anotação</option><option value="call">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="meeting">Reunião</option></select><select className={control} value={form.contact_id} onChange={(e)=>setForm({...form,contact_id:e.target.value})}><option value="">Sem contato</option>{contacts.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className={control} placeholder="Título" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><textarea className={control} rows={4} placeholder="Detalhes" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/><Button disabled={pending||form.title.length<2} onClick={submit}>{pending&&<Loader2 className="animate-spin"/>}Registrar</Button></DialogContent></Dialog> }
function TaskDialog({ open,onClose,opportunity,contacts }: { open:boolean; onClose:()=>void; opportunity:Opportunity; contacts:CrmContact[] }) { const router=useRouter(); const [pending,startTransition]=useTransition(); const [form,setForm]=useState({type:'follow_up',title:'',description:'',contact_id:'',due_at:'',priority:'normal'}); const submit=()=>startTransition(async()=>{const result=await createTask({opportunity_id:opportunity.id,customer_id:opportunity.customer_id,contact_id:form.contact_id||null,type:form.type,title:form.title,description:form.description||null,due_at:new Date(form.due_at).toISOString(),priority:form.priority});if(!result.success)toast.error(result.error);else{toast.success('Tarefa criada.');onClose();router.refresh()}}); return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>Nova tarefa</DialogTitle></DialogHeader><select className={control} value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}><option value="follow_up">Follow-up</option><option value="call">Ligação</option><option value="whatsapp">WhatsApp</option><option value="email">E-mail</option><option value="meeting">Reunião</option><option value="send_quote">Enviar orçamento</option><option value="return_contact">Retornar contato</option><option value="other">Outra</option></select><input className={control} placeholder="Título" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><input type="datetime-local" className={control} value={form.due_at} onChange={(e)=>setForm({...form,due_at:e.target.value})}/><select className={control} value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value})}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select><select className={control} value={form.contact_id} onChange={(e)=>setForm({...form,contact_id:e.target.value})}><option value="">Sem contato</option>{contacts.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea className={control} placeholder="Detalhes" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/><Button disabled={pending||form.title.length<2||!form.due_at} onClick={submit}>{pending&&<Loader2 className="animate-spin"/>}Criar tarefa</Button></DialogContent></Dialog> }
