'use client'

import { useState,useTransition } from 'react'
import Image from 'next/image'
import { CheckCircle2,ExternalLink,Loader2,MessageSquareText,Palette,ShieldCheck } from 'lucide-react'
import { respondToArt } from '@/app/arte/actions'
import type { PublicArt } from '@/types/operations'

export function PublicArtApproval({art,token}:{art:PublicArt;token:string}){
  const [mode,setMode]=useState<'approve'|'request_change'|null>(null);const [name,setName]=useState('');const [changeText,setChangeText]=useState('');const [done,setDone]=useState('');const [error,setError]=useState('');const [pending,start]=useTransition();const isPdf=art.preview_url?.toLowerCase().includes('.pdf')
  const submit=()=>mode&&start(async()=>{const result=await respondToArt(mode,{token,name,changeText:mode==='request_change'?changeText:null});if(!result.success){setError(result.error??'Não foi possível responder.');return}setDone(mode==='approve'?'Arte aprovada com sucesso.':'Solicitação de alteração enviada.');setMode(null)})
  return <main className="min-h-screen bg-[#f3f4f1] p-3 text-zinc-950 sm:p-8">
    <article className="mx-auto max-w-4xl overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">
      <header className="bg-zinc-950 p-5 text-white sm:p-8"><p className="text-sm font-semibold tracking-[.18em] text-green-400">SELMA BORDADOS</p><div className="mt-3 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><h1 className="text-2xl font-semibold sm:text-3xl">Aprovação de arte</h1><p className="mt-1 text-sm text-zinc-400">Pedido #{art.order_number} · versão {art.version_number}</p></div><span className="w-fit rounded-full bg-white/10 px-3 py-1 text-xs uppercase">{statusLabel(art.status)}</span></div></header>
      <div className="space-y-6 p-5 sm:p-8">
        <section className="grid gap-4 rounded-xl bg-zinc-50 p-4 sm:grid-cols-2"><Info label="Cliente" value={art.customer_name}/><Info label="Produto" value={art.item?.model??'Arte geral do pedido'}/><Info label="Posição" value={art.placement??'Conforme mockup'}/><Info label="Medidas" value={art.width&&art.height?`${art.width} × ${art.height} cm`:'Conforme mockup'}/></section>
        <section><div className="mb-3 flex items-center gap-2"><Palette className="size-5"/><h2 className="font-semibold">Mockup apresentado</h2></div>{art.preview_url?(isPdf?<a className="flex min-h-64 items-center justify-center rounded-xl border border-zinc-200 bg-zinc-50 font-medium text-green-700" href={art.preview_url} target="_blank" rel="noreferrer"><ExternalLink className="mr-2"/>Abrir arte em PDF</a>:<Image unoptimized width={1200} height={800} sizes="(max-width: 640px) 100vw, 896px" src={art.preview_url} alt={`Arte do pedido ${art.order_number}`} className="max-h-[70vh] w-full rounded-xl border border-zinc-200 object-contain"/>):<div className="rounded-xl bg-amber-50 p-6 text-center text-amber-800">A prévia segura não está disponível.</div>}</section>
        <section className="grid gap-4 sm:grid-cols-2"><Info label="Descrição" value={art.description}/><Info label="Cores" value={art.colors?.join(', ')||'Conforme mockup'}/></section>
        {art.customer_notes&&<section className="rounded-xl border border-zinc-200 p-4"><p className="text-xs font-semibold uppercase text-zinc-500">Observação</p><p className="mt-2 whitespace-pre-wrap text-sm">{art.customer_notes}</p></section>}
        {(done||!art.can_respond)&&<div className="flex gap-3 rounded-xl bg-green-50 p-4 text-green-800"><ShieldCheck className="size-5 shrink-0"/><strong>{done||'Esta arte já recebeu uma resposta.'}</strong></div>}
        {art.can_respond&&!done&&<div className="grid gap-3 sm:grid-cols-2"><button onClick={()=>{setMode('approve');setError('')}} className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-green-600 px-4 font-semibold text-white hover:bg-green-700"><CheckCircle2/>Aprovar arte</button><button onClick={()=>{setMode('request_change');setError('')}} className="flex min-h-12 items-center justify-center gap-2 rounded-xl border border-zinc-300 px-4 font-semibold hover:bg-zinc-50"><MessageSquareText/>Solicitar alteração</button></div>}
        {mode&&<section className="space-y-3 rounded-xl border border-zinc-200 bg-zinc-50 p-4"><div><h2 className="font-semibold">{mode==='approve'?'Confirmar aprovação':'Descreva o que precisa ser alterado'}</h2><p className="text-sm text-zinc-500">A resposta será vinculada exatamente a esta versão.</p></div><label className="block text-sm">Seu nome *<input className="mt-1 w-full rounded-lg border border-zinc-300 bg-white p-2.5 outline-none focus:border-green-600" value={name} onChange={event=>setName(event.target.value)}/></label>{mode==='request_change'&&<label className="block text-sm">Alteração solicitada *<textarea className="mt-1 min-h-28 w-full rounded-lg border border-zinc-300 bg-white p-2.5 outline-none focus:border-green-600" value={changeText} onChange={event=>setChangeText(event.target.value)}/></label>}{error&&<p className="text-sm text-red-600">{error}</p>}<div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button className="rounded-lg border px-4 py-2" onClick={()=>setMode(null)}>Cancelar</button><button disabled={pending||name.trim().length<2||(mode==='request_change'&&changeText.trim().length<3)} onClick={submit} className="rounded-lg bg-zinc-950 px-4 py-2 font-medium text-white disabled:opacity-50">{pending&&<Loader2 className="mr-1 inline size-4 animate-spin"/>}Confirmar</button></div></section>}
      </div>
      <footer className="border-t border-zinc-200 p-5 text-center text-xs text-zinc-500">Selma Bordados · Pedido #{art.order_number} · Arte v{art.version_number}</footer>
    </article>
  </main>
}
function Info({label,value}:{label:string;value:string}){return <div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-zinc-500">{label}</p><p className="mt-1 break-words font-medium">{value}</p></div>}
function statusLabel(status:string){return({sent:'Aguardando resposta',viewed:'Visualizada',approved:'Aprovada',change_requested:'Alteração solicitada'} as Record<string,string>)[status]??status}
