'use client'

import { useMemo,useState,useTransition } from 'react'
import Link from 'next/link'
import { AlertTriangle,Building2,CheckCircle2,Loader2,PackagePlus,ReceiptText,Send,ShoppingCart,Truck } from 'lucide-react'
import { toast } from 'sonner'
import { createPurchaseOrder,createSupplier,receivePurchase,setPurchaseOrderStatus } from '@/app/operacional/actions'
import { EmptyState,HealthBadge,MetricCard,SectionCard } from '@/components/crm/CrmUi'
import { Button } from '@/components/ui/button'
import { Tabs,TabsContent,TabsList,TabsTrigger } from '@/components/ui/tabs'
import { formatBRL,formatDate } from '@/lib/utils'

type Suggestion={fabric_id:string;codigo:string;descricao:string;unit:string;preferred_supplier_id:string|null;impacted_orders:string[];physical_quantity:number;in_purchase_quantity:number;required_quantity:number;reserved_quantity:number;available_quantity:number;shortage_quantity:number;suggested_quantity:number;valor_unitario:number|null}
type Supplier={id:string;name:string;document:string|null;phone:string|null;email:string|null;contact:string|null;lead_time_days:number;notes:string|null;active:boolean}
type PurchaseItem={id:string;fabric_id:string;description:string;quantity:number;received_quantity:number;unit:string;unit_cost:number;total:number;required_for_order_id:string|null}
type PurchaseOrder={id:string;number:string;status:string;expected_date:string|null;total:number;created_at:string;supplier:Supplier|Supplier[]|null;items:PurchaseItem[]}
type Workspace={available:boolean;suggestions:unknown[];orders:unknown[];suppliers:unknown[]}
type Result={success:boolean;error?:string}

export function PurchasingWorkspace({workspace,fallback}:{workspace:Workspace;fallback:React.ReactNode}){
  const suggestions=workspace.suggestions as Suggestion[];const orders=workspace.orders as PurchaseOrder[];const suppliers=workspace.suppliers as Supplier[];const [pending,start]=useTransition();const [selected,setSelected]=useState<Suggestion|null>(null)
  const shortageTotal=useMemo(()=>suggestions.reduce((sum,item)=>sum+Number(item.suggested_quantity),0),[suggestions]);const openOrders=orders.filter(order=>!['received','cancelled'].includes(order.status));const received=orders.filter(order=>order.status==='received')
  const run=(work:()=>Promise<Result>,message:string,onSuccess?:()=>void)=>start(async()=>{const result=await work();if(!result.success){toast.error(result.error??'Não foi possível concluir a ação.');return}toast.success(message);onSuccess?.();location.reload()})
  if(!workspace.available)return <>{fallback}</>
  return <div className="space-y-5 p-4 sm:p-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard compact label="Itens com necessidade" value={suggestions.length} icon={<AlertTriangle/>} tone={suggestions.length?'warning':'success'}/><MetricCard compact label="Quantidade sugerida" value={number(shortageTotal)} icon={<ShoppingCart/>}/><MetricCard compact label="Pedidos em aberto" value={openOrders.length} icon={<Truck/>} tone={openOrders.length?'warning':'neutral'}/><MetricCard compact label="Recebidos" value={received.length} icon={<CheckCircle2/>} tone="success"/></div>
    <Tabs defaultValue="needs"><div className="overflow-x-auto"><TabsList variant="line" className="min-w-max"><TabsTrigger value="needs">Necessidades</TabsTrigger><TabsTrigger value="orders">Pedidos de compra</TabsTrigger><TabsTrigger value="suppliers">Fornecedores</TabsTrigger><TabsTrigger value="receipts">Recebimentos</TabsTrigger></TabsList></div>
      <TabsContent value="needs"><SectionCard title="Sugestões consolidadas" description="Combina faltas dos pedidos e estoque mínimo, descontando compras abertas.">{suggestions.length?<div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Material</th><th>Necessário</th><th>Disponível</th><th>Reservado</th><th>Em compra</th><th>Faltante</th><th>Sugerido</th><th>Pedidos impactados</th><th/></tr></thead><tbody>{suggestions.map(item=><tr key={item.fabric_id}><td><strong>{item.codigo} · {item.descricao}</strong><span className="block text-xs text-muted">{unit(item.unit)}</span></td><td>{number(item.required_quantity)}</td><td>{number(item.available_quantity)}</td><td>{number(item.reserved_quantity)}</td><td>{number(item.in_purchase_quantity)}</td><td>{Number(item.shortage_quantity)>0?<HealthBadge kind="danger" label={number(item.shortage_quantity)}/>:<HealthBadge kind="success" label="Coberto"/>}</td><td><HealthBadge kind="warning" label={number(item.suggested_quantity)}/></td><td><div className="flex flex-wrap gap-1">{item.impacted_orders?.map(id=><Link key={id} href={`/pedidos/${id}`} className="text-xs text-green-600 hover:underline">Ver pedido</Link>)}</div></td><td>{!item.preferred_supplier_id&&<p className="mb-1 text-xs text-amber-600">Fornecedor não definido</p>}<Button size="sm" disabled={!suppliers.length} onClick={()=>setSelected(item)}><PackagePlus/>Gerar compra</Button></td></tr>)}</tbody></table></div>:<EmptyState title="Nenhuma compra sugerida" description="O estoque e as necessidades dos pedidos estão cobertos."/>}</SectionCard>{selected&&<CreateOrderForm suggestion={selected} suppliers={suppliers} pending={pending} onCancel={()=>setSelected(null)} run={run}/>}</TabsContent>
      <TabsContent value="orders"><Orders orders={orders} pending={pending} run={run}/></TabsContent>
      <TabsContent value="suppliers"><Suppliers suppliers={suppliers} pending={pending} run={run}/></TabsContent>
      <TabsContent value="receipts"><Receipts orders={orders} pending={pending} run={run}/></TabsContent>
    </Tabs>
  </div>
}

function CreateOrderForm({suggestion,suppliers,pending,onCancel,run}:{suggestion:Suggestion;suppliers:Supplier[];pending:boolean;onCancel:()=>void;run:(work:()=>Promise<Result>,message:string,onSuccess?:()=>void)=>void}){const [supplierId,setSupplierId]=useState(suggestion.preferred_supplier_id??suppliers[0]?.id??'');const [quantity,setQuantity]=useState(Number(suggestion.suggested_quantity));const [cost,setCost]=useState(Number(suggestion.valor_unitario??0));const [expected,setExpected]=useState('');return <SectionCard title={`Nova compra · ${suggestion.codigo}`} description="A quantidade pode ser ajustada antes de criar o pedido."><div className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5"><Field label="Fornecedor"><select className="crm-control" value={supplierId} onChange={event=>setSupplierId(event.target.value)}>{suppliers.filter(row=>row.active).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Quantidade"><input className="crm-control" type="number" min="0.0001" step="0.0001" value={quantity} onChange={event=>setQuantity(Number(event.target.value))}/></Field><Field label="Unidade"><input className="crm-control" disabled value={unit(suggestion.unit)}/></Field><Field label="Custo unitário"><input className="crm-control" type="number" min="0" step="0.01" value={cost} onChange={event=>setCost(Number(event.target.value))}/></Field><Field label="Previsão"><input className="crm-control" type="date" value={expected} onChange={event=>setExpected(event.target.value)}/></Field><div className="flex gap-2 sm:col-span-2 lg:col-span-5 lg:justify-end"><Button variant="outline" onClick={onCancel}>Cancelar</Button><Button disabled={pending||!supplierId||quantity<=0} onClick={()=>run(()=>createPurchaseOrder({supplierId,expectedDate:expected||null,notes:`Sugestão automática para ${suggestion.codigo}`,items:[{fabric_id:suggestion.fabric_id,description:suggestion.descricao,quantity,unit:suggestion.unit,unit_cost:cost,required_for_order_id:suggestion.impacted_orders?.length===1?suggestion.impacted_orders[0]:null,position:0}]}),'Pedido de compra criado.',onCancel)}>{pending?<Loader2 className="animate-spin"/>:<ShoppingCart/>}Criar pedido</Button></div></div></SectionCard>}

function Orders({orders,pending,run}:{orders:PurchaseOrder[];pending:boolean;run:(work:()=>Promise<Result>,message:string)=>void}){return <SectionCard title="Pedidos de compra" description="Envio, confirmação e cobertura das necessidades.">{orders.length?<div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Número</th><th>Fornecedor</th><th>Status</th><th>Previsão</th><th>Total</th><th>Itens</th><th/></tr></thead><tbody>{orders.map(order=>{const supplier=Array.isArray(order.supplier)?order.supplier[0]:order.supplier;return <tr key={order.id}><td><strong>{order.number}</strong></td><td>{supplier?.name??'—'}</td><td><PurchaseStatus status={order.status}/></td><td>{formatDate(order.expected_date)}</td><td>{formatBRL(Number(order.total))}</td><td>{order.items?.length??0}</td><td><div className="flex gap-1">{order.status==='draft'&&<Button size="sm" variant="outline" disabled={pending} onClick={()=>run(()=>setPurchaseOrderStatus(order.id,'sent'),'Pedido marcado como enviado.')}><Send/>Enviar</Button>}{order.status==='sent'&&<Button size="sm" variant="outline" disabled={pending} onClick={()=>run(()=>setPurchaseOrderStatus(order.id,'confirmed'),'Pedido confirmado pelo fornecedor.')}>Confirmar</Button>}</div></td></tr>})}</tbody></table></div>:<EmptyState title="Nenhum pedido de compra" description="Gere o primeiro pedido a partir de uma necessidade consolidada."/>}</SectionCard>}

function Suppliers({suppliers,pending,run}:{suppliers:Supplier[];pending:boolean;run:(work:()=>Promise<Result>,message:string)=>void}){const submit=(formData:FormData)=>run(()=>createSupplier({name:String(formData.get('name')),document:text(formData.get('document')),phone:text(formData.get('phone')),email:text(formData.get('email')),contact:text(formData.get('contact')),lead_time_days:Number(formData.get('leadTime')),notes:text(formData.get('notes'))}),'Fornecedor cadastrado.');return <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><SectionCard title="Novo fornecedor"><form action={submit} className="space-y-3 p-4"><Field label="Razão social / nome"><input required name="name" minLength={2} className="crm-control"/></Field><Field label="CNPJ / documento"><input name="document" className="crm-control"/></Field><Field label="Contato"><input name="contact" className="crm-control"/></Field><div className="grid grid-cols-2 gap-2"><Field label="Telefone"><input name="phone" className="crm-control"/></Field><Field label="E-mail"><input name="email" type="email" className="crm-control"/></Field></div><Field label="Prazo médio (dias)"><input name="leadTime" type="number" min="0" max="365" defaultValue="7" className="crm-control"/></Field><Field label="Observação"><textarea name="notes" className="crm-control min-h-20 py-2"/></Field><Button disabled={pending} className="w-full"><Building2/>Cadastrar</Button></form></SectionCard><SectionCard title="Fornecedores ativos">{suppliers.length?<div className="divide-y" style={{borderColor:'var(--border-subtle)'}}>{suppliers.map(row=><div key={row.id} className="flex items-center justify-between gap-3 p-4 text-sm"><div><strong>{row.name}</strong><p className="text-xs text-muted">{[row.contact,row.phone,row.email].filter(Boolean).join(' · ')||'Sem contato'}</p></div><span className="text-xs text-muted">Prazo: {row.lead_time_days} dias</span></div>)}</div>:<EmptyState title="Nenhum fornecedor" description="Cadastre um fornecedor para emitir pedidos de compra."/>}</SectionCard></div>}

function Receipts({orders,pending,run}:{orders:PurchaseOrder[];pending:boolean;run:(work:()=>Promise<Result>,message:string)=>void}){const eligible=orders.filter(order=>['sent','confirmed','partial'].includes(order.status));const [orderId,setOrderId]=useState(eligible[0]?.id??'');const order=eligible.find(row=>row.id===orderId);const [quantities,setQuantities]=useState<Record<string,number>>({});const receive=()=>{if(!order)return;const items=order.items.map(item=>({item_id:item.id,quantity:Number(quantities[item.id]??0)})).filter(item=>item.quantity>0);run(()=>receivePurchase({purchaseOrderId:order.id,operationId:crypto.randomUUID(),invoiceNumber:null,notes:null,items}),'Recebimento registrado e estoque atualizado.')};return <SectionCard title="Recebimento parcial" description="Cada confirmação gera uma entrada de estoque auditável e idempotente.">{eligible.length?<div className="space-y-4 p-4"><Field label="Pedido"><select className="crm-control max-w-md" value={orderId} onChange={event=>{setOrderId(event.target.value);setQuantities({})}}>{eligible.map(row=><option key={row.id} value={row.id}>{row.number}</option>)}</select></Field><div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Material</th><th>Comprado</th><th>Já recebido</th><th>Receber agora</th></tr></thead><tbody>{order?.items.map(item=><tr key={item.id}><td>{item.description}</td><td>{number(item.quantity)} {unit(item.unit)}</td><td>{number(item.received_quantity)} {unit(item.unit)}</td><td><input aria-label={`Quantidade recebida de ${item.description}`} className="crm-control w-32" type="number" min="0" max={Number(item.quantity)-Number(item.received_quantity)} step="0.0001" value={quantities[item.id]??''} onChange={event=>setQuantities(current=>({...current,[item.id]:Number(event.target.value)}))}/></td></tr>)}</tbody></table></div><div className="flex justify-end"><Button disabled={pending||!Object.values(quantities).some(value=>value>0)} onClick={receive}><ReceiptText/>Confirmar recebimento</Button></div></div>:<EmptyState title="Nada aguardando recebimento" description="Envie ou confirme um pedido de compra para registrar a chegada."/>}</SectionCard>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block min-w-0 text-xs text-muted">{label}<span className="mt-1 block">{children}</span></label>}
function number(value:number){return Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:4})}
function unit(value:string){return{kg:'kg',meter:'m',unit:'un',sheet:'folha',roll:'rolo',other:'outra'}[value]??value}
function text(value:FormDataEntryValue|null){const output=String(value??'').trim();return output||null}
function PurchaseStatus({status}:{status:string}){const map:Record<string,['neutral'|'warning'|'success'|'danger',string]>={draft:['neutral','Rascunho'],sent:['warning','Enviado'],confirmed:['warning','Confirmado'],partial:['warning','Parcial'],received:['success','Recebido'],cancelled:['danger','Cancelado']};const item=map[status]??['neutral',status];return <HealthBadge kind={item[0]} label={item[1]}/>}
