'use client'

import { useMemo,useState } from 'react'
import Link from 'next/link'
import { AlertTriangle,CalendarClock,Factory,ShieldAlert } from 'lucide-react'
import { EmptyState,HealthBadge,MetricCard,SectionCard } from '@/components/crm/CrmUi'
import { formatDate } from '@/lib/utils'

type Capacity={day:string;workcenter_id:string;code:string;name:string;capacity_unit:string;daily_capacity:number;planned_quantity:number;utilization_percent:number}
type Dashboard={to_release:number;blocked:number;late:number;at_risk:number;capacity:Capacity[];bottleneck:Capacity|null}
type Responsible={full_name:string}
type PlanOrder={id:string;numero:string;cliente:string;entrega_programado:string;production_released_at:string|null;responsible:Responsible|Responsible[]|null}
type Plan={id:string;order_id:string;status:string;requested_delivery_date:string;safe_delivery_date:string|null;committed_delivery_date:string|null;risk_level:string;blocking_reasons:Array<{code:string;label:string;severity:string}>;order:PlanOrder|PlanOrder[]|null}

export function ProductionPlanningDashboard({data}:{data:{available:boolean;dashboard:unknown;plans:unknown[]}}){
  const dashboard=data.dashboard as Dashboard|null;const plans=data.plans as Plan[];const [risk,setRisk]=useState('all');const [status,setStatus]=useState('all');const [client,setClient]=useState('');const [responsible,setResponsible]=useState('');const [deadline,setDeadline]=useState('');const [blockedOnly,setBlockedOnly]=useState(false);const [sector,setSector]=useState('all')
  const visible=useMemo(()=>plans.filter(plan=>{const order=Array.isArray(plan.order)?plan.order[0]:plan.order;const owner=responsibleName(order);return(risk==='all'||plan.risk_level===risk)&&(status==='all'||plan.status===status)&&(!client||order?.cliente.toLowerCase().includes(client.toLowerCase()))&&(!responsible||owner.toLowerCase().includes(responsible.toLowerCase()))&&(!deadline||String(plan.safe_delivery_date??plan.requested_delivery_date)<=deadline)&&(!blockedOnly||plan.blocking_reasons?.length>0)}),[plans,risk,status,client,responsible,deadline,blockedOnly])
  if(!data.available||!dashboard)return <SectionCard title="PCP"><EmptyState icon={<Factory/>} title="PCP aguardando homologação" description="A migration do planejamento ainda não está aplicada neste banco."/></SectionCard>
  const grouped=groupCapacity(dashboard.capacity??[]);const visibleCenters=sector==='all'?grouped.centers:grouped.centers.filter(center=>center.code===sector)
  return <div className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard compact label="A liberar" value={dashboard.to_release} icon={<CalendarClock/>} tone={dashboard.to_release?'warning':'success'}/><MetricCard compact label="Bloqueados" value={dashboard.blocked} icon={<ShieldAlert/>} tone={dashboard.blocked?'danger':'success'}/><MetricCard compact label="Atrasados" value={dashboard.late} icon={<AlertTriangle/>} tone={dashboard.late?'danger':'success'}/><MetricCard compact label="Em risco" value={dashboard.at_risk} icon={<Factory/>} tone={dashboard.at_risk?'warning':'success'}/></div>
    <SectionCard title="Capacidade dos próximos 15 dias" description={dashboard.bottleneck?`Maior ocupação: ${dashboard.bottleneck.name} em ${formatDate(dashboard.bottleneck.day)} (${Number(dashboard.bottleneck.utilization_percent).toFixed(0)}%).`:'Sem gargalo calculado.'} action={<select aria-label="Filtrar setor" className="crm-control h-9 min-w-36" value={sector} onChange={event=>setSector(event.target.value)}><option value="all">Todos os setores</option>{grouped.centers.map(center=><option key={center.code} value={center.code}>{center.name}</option>)}</select>}><div className="overflow-x-auto"><table className="crm-table min-w-[760px]"><thead><tr><th>Centro</th>{grouped.days.map(day=><th key={day}>{new Date(`${day}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</th>)}</tr></thead><tbody>{visibleCenters.map(center=><tr key={center.code}><td className="sticky left-0 bg-card"><strong>{center.name}</strong><span className="block text-xs text-muted">{number(center.dailyCapacity)} {unit(center.unit)}/dia</span></td>{grouped.days.map(day=>{const utilization=center.values.get(day)??0;return <td key={day}><div className="min-w-14"><span className={utilization>100?'font-semibold text-rose-600':utilization>=85?'font-semibold text-amber-600':'text-muted'}>{utilization.toFixed(0)}%</span><div className="mt-1 h-1.5 overflow-hidden rounded-full bg-surface-hover"><div className={utilization>100?'h-full bg-rose-500':utilization>=85?'h-full bg-amber-500':'h-full bg-green-500'} style={{width:`${Math.min(100,utilization)}%`}}/></div></div></td>})}</tr>)}</tbody></table></div></SectionCard>
    <SectionCard title="Pedidos no planejamento" description="Filtros operacionais por prazo, status, risco, cliente, responsável e bloqueios."><div className="grid gap-2 border-b p-3 sm:grid-cols-2 xl:grid-cols-6" style={{borderColor:'var(--border-subtle)'}}><select aria-label="Filtrar risco" className="crm-control" value={risk} onChange={event=>setRisk(event.target.value)}><option value="all">Todos os riscos</option><option value="safe">Seguro</option><option value="attention">Atenção</option><option value="high_risk">Alto risco</option><option value="impossible">Impossível</option></select><select aria-label="Filtrar status" className="crm-control" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Todos os status</option><option value="blocked">Bloqueado</option><option value="ready">Pronto</option><option value="released">Liberado</option><option value="in_progress">Em produção</option></select><input aria-label="Filtrar cliente" className="crm-control" placeholder="Cliente" value={client} onChange={event=>setClient(event.target.value)}/><input aria-label="Filtrar responsável" className="crm-control" placeholder="Responsável" value={responsible} onChange={event=>setResponsible(event.target.value)}/><input aria-label="Prazo máximo" type="date" className="crm-control" value={deadline} onChange={event=>setDeadline(event.target.value)}/><label className="flex min-h-10 items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={blockedOnly} onChange={event=>setBlockedOnly(event.target.checked)}/>Somente bloqueados</label></div>{visible.length?<div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Responsável</th><th>Status</th><th>Risco</th><th>Solicitado</th><th>Seguro</th><th>Comprometido</th><th>Bloqueios</th></tr></thead><tbody>{visible.map(plan=>{const order=Array.isArray(plan.order)?plan.order[0]:plan.order;return <tr key={plan.id}><td><Link className="font-semibold text-green-600 hover:underline" href={`/pedidos/${plan.order_id}`}>#{order?.numero??'—'}</Link></td><td>{order?.cliente??'—'}</td><td>{responsibleName(order)||'—'}</td><td>{statusLabel(plan.status)}</td><td><RiskBadge risk={plan.risk_level}/></td><td>{formatDate(plan.requested_delivery_date)}</td><td>{formatDate(plan.safe_delivery_date)}</td><td>{formatDate(plan.committed_delivery_date)}</td><td><div className="flex max-w-sm flex-wrap gap-1">{plan.blocking_reasons?.length?plan.blocking_reasons.map(blocker=><HealthBadge key={blocker.code} kind="danger" label={blocker.label}/>):<HealthBadge kind="success" label="Sem bloqueios"/>}</div></td></tr>})}</tbody></table></div>:<EmptyState title="Nenhum pedido neste filtro" description="Ajuste os filtros para consultar os outros planos."/>}</SectionCard>
  </div>
}

function groupCapacity(rows:Capacity[]){const days=[...new Set(rows.map(row=>String(row.day).slice(0,10)))].sort();const map=new Map<string,{code:string;name:string;unit:string;dailyCapacity:number;values:Map<string,number>}>();for(const row of rows){const center=map.get(row.code)??{code:row.code,name:row.name,unit:row.capacity_unit,dailyCapacity:Number(row.daily_capacity),values:new Map<string,number>()};center.values.set(String(row.day).slice(0,10),Number(row.utilization_percent));map.set(row.code,center)}return{days,centers:[...map.values()]}}
function RiskBadge({risk}:{risk:string}){const config:Record<string,['success'|'warning'|'danger'|'neutral',string]>={safe:['success','Seguro'],attention:['warning','Atenção'],high_risk:['danger','Alto risco'],impossible:['danger','Impossível']};const item=config[risk]??['neutral',risk];return <HealthBadge kind={item[0]} label={item[1]}/>}
function statusLabel(status:string){return{blocked:'Bloqueado',ready:'Pronto',released:'Liberado',in_progress:'Em produção'}[status]??status}
function unit(value:string){return{piece:'peças',minute:'min',point:'pontos',meter:'m',hour:'h'}[value]??value}
function number(value:number){return Number(value||0).toLocaleString('pt-BR',{maximumFractionDigits:2})}
function responsibleName(order:PlanOrder|null|undefined){if(!order)return'';const responsible=Array.isArray(order.responsible)?order.responsible[0]:order.responsible;return responsible?.full_name??''}
