'use server'

import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { requirePermission } from '@/lib/auth/require-user'
import { createAdminSupabaseClient } from '@/lib/supabase/admin'
import { createServerSupabaseClient } from '@/lib/supabase/server'
import { createArtStoragePath,LAYOUT_BUCKET,validateLayoutFile } from '@/lib/security/upload'
import { enforceRateLimit } from '@/lib/security/rate-limit'
import { safeDatabaseError } from '@/lib/security/errors'

type Result<T=undefined>={success:boolean;error?:string;data?:T}
const fail=<T=undefined>(error:unknown,message:string):Result<T>=>({success:false,error:safeDatabaseError(error,message,{action:'lot8-operational-action'})})
const uuid=z.string().uuid()

export async function uploadArt(formData:FormData):Promise<Result<{artId:string}>>{
  const context=await requirePermission('art.manage');const orderId=uuid.safeParse(formData.get('orderId'));const itemId=z.union([uuid,z.literal('')]).safeParse(formData.get('orderItemId')??'');const file=formData.get('file')
  if(!orderId.success||!itemId.success||!(file instanceof File))return{success:false,error:'Pedido, item ou arquivo inválido.'}
  const description=z.string().trim().min(2).max(500).safeParse(formData.get('description'));if(!description.success)return{success:false,error:'Informe uma descrição da arte.'}
  const limiter=await enforceRateLimit({scope:'art-upload',identifier:context.user.id,limit:10,windowSeconds:60});if(!limiter.allowed)return{success:false,error:'Muitos uploads. Aguarde um minuto.'}
  const bytes=new Uint8Array(await file.arrayBuffer());const validation=validateLayoutFile(file.name,file.type,file.size,bytes);if(!validation.ok)return{success:false,error:validation.message}
  const admin=createAdminSupabaseClient();const path=createArtStoragePath(orderId.data,validation.extension);const uploaded=await admin.storage.from(LAYOUT_BUCKET).upload(path,bytes,{contentType:validation.mime,upsert:false});if(uploaded.error)return fail<{artId:string}>(uploaded.error,'Não foi possível enviar a arte.')
  const supabase=await createServerSupabaseClient();const colors=String(formData.get('colors')??'').split(',').map(value=>value.trim()).filter(Boolean).slice(0,20)
  const {data,error}=await supabase.rpc('create_art_version',{p_order_id:orderId.data,p_order_item_id:itemId.data||null,p_file_path:path,p_description:description.data,p_width:numberOrNull(formData.get('width')),p_height:numberOrNull(formData.get('height')),p_placement:textOrNull(formData.get('placement')),p_colors:colors,p_internal_notes:textOrNull(formData.get('internalNotes')),p_customer_notes:textOrNull(formData.get('customerNotes'))})
  if(error||!data){await admin.storage.from(LAYOUT_BUCKET).remove([path]);return fail<{artId:string}>(error,'Não foi possível criar a versão da arte.')}
  refreshOrder(orderId.data);return{success:true,data:{artId:String(data)}}
}

export async function sendArt(artId:string,orderId:string):Promise<Result<{token:string}>>{await requirePermission('art.manage');const parsed=uuid.safeParse(artId);const order=uuid.safeParse(orderId);if(!parsed.success||!order.success)return{success:false,error:'Arte inválida.'};const supabase=await createServerSupabaseClient();const {data,error}=await supabase.rpc('send_art_version',{p_art_id:parsed.data,p_valid_days:15});if(error||!data)return fail<{token:string}>(error,'Não foi possível gerar o link da arte.');refreshOrder(order.data);return{success:true,data:{token:String((data as {token:string}).token)}}}

export async function setArtRequirement(orderId:string,required:boolean):Promise<Result>{await requirePermission('art.manage');const parsed=uuid.safeParse(orderId);if(!parsed.success||typeof required!=='boolean')return{success:false,error:'Pedido ou condição de arte inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('set_order_art_requirement',{p_order_id:parsed.data,p_required:required});if(error)return fail(error,'Não foi possível alterar a exigência de arte.');refreshOrder(parsed.data);return{success:true}}

const sheetSchema=z.object({orderId:uuid,orderItemId:uuid,productName:z.string().trim().min(2).max(200),model:z.string().trim().max(160).nullable(),fabric:z.string().trim().max(160).nullable(),color:z.string().trim().max(100).nullable(),customizationType:z.enum(['embroidery','silk','dtf','sublimation','none','other']),constructionNotes:z.string().trim().max(4000).nullable(),measurementNotes:z.string().trim().max(4000).nullable(),productionNotes:z.string().trim().max(4000).nullable(),artApprovalId:uuid.nullable(),gradeSnapshot:z.array(z.object({size:z.string().max(30),quantity:z.number().nonnegative()}).strict()).max(100)}).strict()
export async function saveTechnicalSheet(input:unknown):Promise<Result>{await requirePermission('production.update');const parsed=sheetSchema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Ficha técnica inválida.'};const {orderId,orderItemId,...sheet}=parsed.data;const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('save_technical_sheet',{p_order_id:orderId,p_order_item_id:orderItemId,p_payload:{product_name:sheet.productName,model:sheet.model,fabric:sheet.fabric,color:sheet.color,customization_type:sheet.customizationType,construction_notes:sheet.constructionNotes,measurement_notes:sheet.measurementNotes,production_notes:sheet.productionNotes,art_approval_id:sheet.artApprovalId,grade_snapshot:sheet.gradeSnapshot}});if(error)return fail(error,'Não foi possível salvar a ficha técnica.');refreshOrder(orderId);return{success:true}}

const bomItem=z.object({fabric_id:uuid.nullable(),material_type:z.enum(['fabric','thread','ink','paper','trim','packaging','service','other']),description:z.string().trim().min(2).max(200),quantity_per_unit:z.coerce.number().positive(),waste_percent:z.coerce.number().min(0).max(100),unit:z.enum(['kg','meter','unit','sheet','roll','minute','hour','other']),source:z.enum(['manual','template','calculated']),notes:z.string().trim().max(1000).nullable(),position:z.number().int().nonnegative()}).strict()
const bomSchema=z.object({orderId:uuid,orderItemId:uuid.nullable(),source:z.enum(['manual','template','calculated']),items:z.array(bomItem).min(1).max(100)}).strict()
export async function saveBom(input:unknown):Promise<Result>{await requirePermission('production.update');const parsed=bomSchema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'BOM inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('save_bill_of_materials',{p_order_id:parsed.data.orderId,p_order_item_id:parsed.data.orderItemId,p_source:parsed.data.source,p_items:parsed.data.items});if(error)return fail(error,'Não foi possível salvar a necessidade de materiais.');refreshOrder(parsed.data.orderId);return{success:true}}

export async function reserveMaterials(orderId:string):Promise<Result<{reserved:number;shortage:number}>>{await requirePermission('production.update');const parsed=uuid.safeParse(orderId);if(!parsed.success)return{success:false,error:'Pedido inválido.'};const supabase=await createServerSupabaseClient();const {data,error}=await supabase.rpc('reserve_order_materials',{p_order_id:parsed.data});if(error)return fail<{reserved:number;shortage:number}>(error,'Não foi possível reservar os materiais.');refreshOrder(parsed.data);return{success:true,data:data as {reserved:number;shortage:number}}}

export async function recalculatePlan(orderId:string,committedDate:string|null=null):Promise<Result>{await requirePermission('production.update');const parsed=uuid.safeParse(orderId);const date=z.string().date().nullable().safeParse(committedDate);if(!parsed.success||!date.success)return{success:false,error:'Pedido ou data inválida.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('recalculate_production_plan',{p_order_id:parsed.data,p_committed_date:date.data,p_notes:null});if(error)return fail(error,'Não foi possível calcular o planejamento.');refreshOrder(parsed.data);revalidatePath('/producao');return{success:true}}

export async function releaseOrder(input:unknown):Promise<Result>{await requirePermission('production.update');const parsed=z.object({orderId:uuid,committedDate:z.string().date(),overrideReason:z.string().trim().max(1000).nullable(),operationId:uuid}).strict().safeParse(input);if(!parsed.success)return{success:false,error:'Dados de liberação inválidos.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('release_order_to_production',{p_order_id:parsed.data.orderId,p_committed_date:parsed.data.committedDate,p_override_reason:parsed.data.overrideReason,p_operation_id:parsed.data.operationId});if(error)return fail(error,'O pedido ainda possui bloqueios para produção.');refreshOrder(parsed.data.orderId);revalidatePath('/producao');return{success:true}}

const supplierSchema=z.object({name:z.string().trim().min(2).max(160),document:z.string().trim().max(30).nullable(),phone:z.string().trim().max(40).nullable(),email:z.string().email().nullable(),contact:z.string().trim().max(120).nullable(),lead_time_days:z.coerce.number().int().min(0).max(365),notes:z.string().trim().max(1000).nullable()}).strict()
export async function createSupplier(input:unknown):Promise<Result>{await requirePermission('purchases.update');const parsed=supplierSchema.safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Fornecedor inválido.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.from('suppliers').insert(parsed.data);if(error)return fail(error,'Não foi possível cadastrar o fornecedor.');revalidatePath('/compras');return{success:true}}

const purchaseItem=z.object({fabric_id:uuid,description:z.string().trim().min(2).max(200),quantity:z.coerce.number().positive(),unit:z.enum(['kg','meter','unit','sheet','roll','other']),unit_cost:z.coerce.number().nonnegative(),required_for_order_id:uuid.nullable(),position:z.number().int().nonnegative()}).strict()
export async function createPurchaseOrder(input:unknown):Promise<Result>{await requirePermission('purchases.create');const parsed=z.object({supplierId:uuid,expectedDate:z.string().date().nullable(),notes:z.string().trim().max(1000).nullable(),items:z.array(purchaseItem).min(1).max(200)}).strict().safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Pedido de compra inválido.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('create_purchase_order',{p_supplier_id:parsed.data.supplierId,p_expected_date:parsed.data.expectedDate,p_notes:parsed.data.notes,p_items:parsed.data.items});if(error)return fail(error,'Não foi possível gerar o pedido de compra.');revalidatePath('/compras');return{success:true}}

export async function setPurchaseOrderStatus(purchaseOrderId:string,status:'sent'|'confirmed'|'cancelled'):Promise<Result>{await requirePermission('purchases.update');const id=uuid.safeParse(purchaseOrderId);const next=z.enum(['sent','confirmed','cancelled']).safeParse(status);if(!id.success||!next.success)return{success:false,error:'Pedido de compra ou status inválido.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('set_purchase_order_status',{p_purchase_order_id:id.data,p_status:next.data});if(error)return fail(error,'Não foi possível atualizar o pedido de compra.');revalidatePath('/compras');return{success:true}}

export async function receivePurchase(input:unknown):Promise<Result>{await requirePermission('purchases.update');const parsed=z.object({purchaseOrderId:uuid,operationId:uuid,invoiceNumber:z.string().trim().max(80).nullable(),notes:z.string().trim().max(1000).nullable(),items:z.array(z.object({item_id:uuid,quantity:z.coerce.number().positive()}).strict()).min(1).max(200)}).strict().safeParse(input);if(!parsed.success)return{success:false,error:parsed.error.issues[0]?.message??'Recebimento inválido.'};const supabase=await createServerSupabaseClient();const {error}=await supabase.rpc('receive_purchase_order',{p_purchase_order_id:parsed.data.purchaseOrderId,p_operation_id:parsed.data.operationId,p_invoice_number:parsed.data.invoiceNumber,p_notes:parsed.data.notes,p_items:parsed.data.items});if(error)return fail(error,'Não foi possível receber o material.');revalidatePath('/compras');revalidatePath('/estoque');revalidatePath('/producao');return{success:true}}

function refreshOrder(id:string){revalidatePath(`/pedidos/${id}`);revalidatePath('/pedidos');revalidatePath('/producao');revalidatePath('/compras')}
function textOrNull(value:FormDataEntryValue|null){const text=String(value??'').trim();return text||null}
function numberOrNull(value:FormDataEntryValue|null){const text=String(value??'').trim();if(!text)return null;const number=Number(text);return Number.isFinite(number)&&number>0?number:null}
